// schemas.go serves golc_list_schemas and golc_get_schema over the
// committed schemas/*.schema.json directory (every schema is generated by
// internal/contracts and checked in, so reading it off disk is always
// exactly what "golc.ps1 check --offline" already validated against).
// Both tools resolve the requested name against a directory listing
// rather than joining untrusted input straight into a path, so a
// caller can never read outside schemas/.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
)

const schemasRelDir = "schemas"
const schemaFileSuffix = ".schema.json"

type listSchemasInput struct{}

type schemaSummary struct {
	Name    string `json:"name"`
	File    string `json:"file"`
	Comment string `json:"comment,omitempty"`
	ID      string `json:"id,omitempty"`
}

type listSchemasOutput struct {
	Schemas []schemaSummary `json:"schemas"`
}

func handleListSchemas(_ context.Context, _ *mcp.CallToolRequest, _ listSchemasInput) (*mcp.CallToolResult, listSchemasOutput, error) {
	root, err := resolveRepoRoot()
	if err != nil {
		return toolError[listSchemasOutput](err)
	}
	dir := filepath.Join(root, schemasRelDir)
	entries, err := os.ReadDir(dir)
	if err != nil {
		return toolError[listSchemasOutput](fmt.Errorf("read %s: %w", schemasRelDir, err))
	}

	var out listSchemasOutput
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), schemaFileSuffix) {
			continue
		}
		name := strings.TrimSuffix(entry.Name(), schemaFileSuffix)
		summary := schemaSummary{Name: name, File: schemasRelDir + "/" + entry.Name()}

		data, readErr := os.ReadFile(filepath.Join(dir, entry.Name()))
		if readErr == nil {
			var header struct {
				Comment string `json:"$comment"`
				ID      string `json:"$id"`
			}
			if json.Unmarshal(data, &header) == nil {
				summary.Comment = header.Comment
				summary.ID = header.ID
			}
		}
		out.Schemas = append(out.Schemas, summary)
	}
	sort.Slice(out.Schemas, func(i, j int) bool { return out.Schemas[i].Name < out.Schemas[j].Name })

	return nil, out, nil
}

type getSchemaInput struct {
	Name string `json:"name" jsonschema:"schema name without the .schema.json suffix, e.g. \"fixture\" or \"config-runtime\" (see golc_list_schemas)"`
}

type getSchemaOutput struct {
	Name   string `json:"name"`
	File   string `json:"file"`
	Schema any    `json:"schema"`
}

func handleGetSchema(_ context.Context, _ *mcp.CallToolRequest, input getSchemaInput) (*mcp.CallToolResult, getSchemaOutput, error) {
	root, err := resolveRepoRoot()
	if err != nil {
		return toolError[getSchemaOutput](err)
	}
	dir := filepath.Join(root, schemasRelDir)
	entries, err := os.ReadDir(dir)
	if err != nil {
		return toolError[getSchemaOutput](fmt.Errorf("read %s: %w", schemasRelDir, err))
	}

	var fileName string
	for _, entry := range entries {
		if !entry.IsDir() && entry.Name() == input.Name+schemaFileSuffix {
			fileName = entry.Name()
			break
		}
	}
	if fileName == "" {
		return toolError[getSchemaOutput](fmt.Errorf("no schema named %q under %s; call golc_list_schemas for the available names", input.Name, schemasRelDir))
	}

	data, err := os.ReadFile(filepath.Join(dir, fileName))
	if err != nil {
		return toolError[getSchemaOutput](fmt.Errorf("read %s/%s: %w", schemasRelDir, fileName, err))
	}
	var schema any
	if err := json.Unmarshal(data, &schema); err != nil {
		return toolError[getSchemaOutput](fmt.Errorf("parse %s/%s: %w", schemasRelDir, fileName, err))
	}

	return nil, getSchemaOutput{Name: input.Name, File: schemasRelDir + "/" + fileName, Schema: schema}, nil
}
