import { afterEach, describe, expect, it } from "vitest";
import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { checkDS007, checkDesignSystem, checkFiles, parseCommandLine } from "./check.mjs";

const roots: string[] = [];

async function fixture(files: Record<string, string>): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), "golc-ds-policy-"));
  roots.push(root);
  for (const [path, source] of Object.entries(files)) {
    const target = join(root, path);
    await mkdir(join(target, ".."), { recursive: true });
    await writeFile(target, source, "utf8");
  }
  return root;
}

afterEach(async () => { await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true }))); });

describe("DS001-DS010 policy boundaries", () => {
  it("parses documented scoped paths and proposal inputs fail-closed", () => {
    expect(parseCommandLine(["--paths", "src/one.tsx,src/two.module.css", "--proposal", "design-system/exception-proposals/fixtures.json"])).toEqual({
      rule: null,
      paths: ["src/one.tsx", "src/two.module.css"],
      proposalPaths: ["design-system/exception-proposals/fixtures.json"],
      wholeSource: false,
    });
    expect(() => parseCommandLine(["--paths"])).toThrow("DSCHECK_ARGS");
    expect(() => parseCommandLine(["--paths", "../outside.tsx"])).toThrow("DSCHECK_ARGS");
  });
  it("DS007 requires one inventory identity for barrel, guide, and tests", async () => {
    const root = await fixture({
      "design-system/components.json": JSON.stringify({ schemaVersion: 1, components: [{ name: "Panel", kind: "primitive", exportPath: "src/components/Panel.tsx", guideAnchor: "#panel", testPath: "src/components/Panel.test.tsx" }] }),
      "src/design-system/index.ts": "export { default as Panel } from '../components/Panel';\n",
      "src/components/Panel.tsx": "export default function Panel() { return null; }\n",
      "src/components/Panel.test.tsx": "export {};\n",
      "DESIGN_SYSTEM.md": "<!-- DESIGN-SYSTEM-INVENTORY:START generated by npm run generate:design-system -->\n#panel\n<!-- DESIGN-SYSTEM-INVENTORY:END -->\n",
    });
    expect((await checkDS007(root)).diagnostics).toEqual([]);
    await writeFile(join(root, "src/design-system/index.ts"), "export { default as Extra } from '../components/Panel';\n");
    expect((await checkDS007(root)).diagnostics[0]).toMatchObject({ rule: "DS007", message: expect.stringContaining("inventory and public barrel exports differ") });
  });
  it.each([
    ["DS001", "src/Feature.module.css", ".panel { color: #fff; }", "raw visual literal"],
    ["DS002", "src/Feature.module.css", ".panel { --feature-color: red; }", "custom property declaration"],
    ["DS003", "src/Feature.module.css", ".panel { color: var(--missing); }", "unknown custom property"],
    ["DS004", "src/Feature.module.css", "[data-theme='dark'] .panel {}", "theme selector"],
    ["DS005", "src/Feature.tsx", "export const Feature = () => <button className='button'>Go</button>;", "styled native control"],
    ["DS006", "src/Feature.module.css", ".primaryButton { padding: 8px; }", "shared visual class"],
    ["DS007", "design-system/components.json", '{"schemaVersion":1,"components":[{"name":"Broken"}', "inventory"],
    ["DS008", "design-system/exceptions.json", '{"schemaVersion":1,"records":[{"path":"src/Feature.module.css"}]}', "exception"],
    ["DS009", "design-system/tokens.json", '{"schemaVersion":1}', "theme contract"],
    ["DS010", "src/Feature.module.css", ".button { outline: none; }", "focus"],
  ])("%s rejects its forbidden fixture", async (rule, path, source, expected) => {
    const root = await fixture({ [path]: source });
    const result = await checkFiles(root, [path]);
    expect(result.diagnostics.some((diagnostic) => diagnostic.rule === rule && diagnostic.message.includes(expected))).toBe(true);
  });

  it("accepts semantic CSS and native semantics inside a public primitive", async () => {
    const root = await fixture({
      "src/Feature.module.css": ".panel { color: var(--ds-text-primary); padding: var(--ds-space-2); }",
      "src/components/primitives/Button/Button.tsx": "export const Button = () => <button className='button'>Go</button>;",
    });
    expect((await checkFiles(root, ["src/Feature.module.css", "src/components/primitives/Button/Button.tsx"])).diagnostics).toEqual([]);
  });

  it("fails closed with stable diagnostics for malformed source and unresolved paths", async () => {
    const root = await fixture({ "src/Feature.module.css": ".panel { color: red" });
    const first = await checkFiles(root, ["src/Feature.module.css", "src/missing.tsx"]);
    const second = await checkFiles(root, ["src/missing.tsx", "src/Feature.module.css"]);
    expect(first.diagnostics).toEqual(second.diagnostics);
    expect(first.diagnostics.every((diagnostic) => diagnostic.rule === "DS000" || diagnostic.path.startsWith("src/"))).toBe(true);
  });

  it("uses the same engine for scoped and full source enumeration", async () => {
    const root = await fixture({
      "src/Feature.module.css": ".panel { color: #fff; }",
      "src/Feature.tsx": "export const Feature = () => <button className='button'>Go</button>;",
    });
    const scoped = await checkDesignSystem(root, { paths: ["src/Feature.module.css", "src/Feature.tsx"] });
    const whole = await checkDesignSystem(root, { wholeSource: true });
    expect(whole.diagnostics).toEqual(scoped.diagnostics);
  });

  it("expands a declared source directory without accepting an unresolved path", async () => {
    const root = await fixture({ "src/Feature/Feature.tsx": "export const Feature = () => <div />;" });
    expect((await checkDesignSystem(root, { paths: ["src/Feature"] })).diagnostics).toEqual([]);
    expect((await checkDesignSystem(root, { paths: ["src/Missing"] })).diagnostics).toMatchObject([{ rule: "DS000" }]);
  });

  it.each([
    ["accepts one exact exception", ".panel { color: #fff; }", "#fff", []],
    ["rejects a stale exception", ".panel { color: #fff; }", "#000", ["stale exception"]],
    ["rejects a broad exception", ".panel { color: #fff; color: #fff; }", "#fff", ["broad exception"]],
    ["never accepts a spacing exception", ".panel { padding: 7px; }", "padding: 7px", ["spacing exception"]],
  ])("%s", async (_name, css, match, messages) => {
    const root = await fixture({
      "src/Feature.module.css": css,
      "design-system/exceptions.json": JSON.stringify({ schemaVersion: 1, records: [{ path: "src/Feature.module.css", rule: "DS001", match, rationale: "domain coordinate", source: "test", owner: "test", reviewCondition: "next review" }] }),
    });
    const result = await checkFiles(root, ["src/Feature.module.css"]);
    expect(messages.length === 0 ? result.diagnostics : result.diagnostics.filter((diagnostic) => messages.includes(diagnostic.message))).toHaveLength(messages.length);
  });
});
