import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { loadDesignSystem } from "./manifest.mjs";

const OUTPUTS = {
  css: "src/design-system/tokens.generated.css",
  types: "src/design-system/tokens.generated.ts",
};

function cssName(role) {
  return `--ds-${role.replaceAll(".", "-")}`;
}

function selector(face) {
  const palette = face.name === "default" ? ":root" : `:root[data-theme-name="${face.name}"]`;
  return `${palette}[data-theme="${face.mode}"]`;
}

// mediaSelector mirrors selector()'s attribute-selector shape, but gated by
// an OS-level prefers-color-scheme media query instead of the explicit
// [data-theme] attribute -- this is what makes "system" mode (theme.ts's
// applyTheme("system"), which removes data-theme entirely) resolve to real
// colors instead of no colors at all, for EVERY theme name, not just
// "default": "system" mode is an independent axis from theme NAME
// (theme.ts's two separate storage keys/attributes), so a user can select
// any named theme while leaving Mode at "Match System". `:not([data-theme])`
// (rather than a bare :root) ensures an explicit stored light/dark
// preference always wins over the OS default: when [data-theme] is present
// this selector simply does not match, independent of source order or
// specificity. The "default" face additionally needs `:not([data-theme-name])`
// -- applyThemeName("default") removes that attribute entirely, so the
// bare-:root branch below only matches when NO theme name is stored at all,
// leaving every non-default name's own `[data-theme-name="..."]` selector as
// the sole match for its own name.
function mediaSelector(face) {
  const palette = face.name === "default" ? ":root:not([data-theme-name])" : `:root[data-theme-name="${face.name}"]`;
  return `${palette}:not([data-theme])`;
}

function renderCSS(tokens) {
  const roles = [...tokens.semanticRoles].sort();
  const faces = [...tokens.themes].sort((a, b) => `${a.name}/${a.mode}`.localeCompare(`${b.name}/${b.mode}`));
  const blocks = faces.map((face) => [selector(face), "{", ...roles.map((role) => `  ${cssName(role)}: ${face.tokens[role]};`), "}"].join("\n"));
  const mediaBlocks = faces.map((face) => [
    `@media (prefers-color-scheme: ${face.mode})`,
    "{",
    `  ${mediaSelector(face)}`,
    "  {",
    ...roles.map((role) => `    ${cssName(role)}: ${face.tokens[role]};`),
    "  }",
    "}",
  ].join("\n"));
  const foundation = Object.entries(tokens.foundation)
    .flatMap(([group, values]) => Object.entries(values).map(([name, value]) => [`--ds-${group}-${name.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`)}`, value]))
    .sort(([a], [b]) => a.localeCompare(b));
  blocks.unshift([":root", "{", ...foundation.map(([name, value]) => `  ${name}: ${value};`), "}"].join("\n"));
  blocks.push(...mediaBlocks);
  return `/* GENERATED by frontend/scripts/design-system/generate.mjs. DO NOT EDIT. */\n${blocks.join("\n\n")}\n`;
}

function renderTypes(tokens) {
  const roles = [...tokens.semanticRoles].sort();
  const names = [...new Set(tokens.themes.map((face) => face.name))].sort();
  const modes = [...new Set(tokens.themes.map((face) => face.mode))].sort();
  return [
    "// GENERATED by frontend/scripts/design-system/generate.mjs. DO NOT EDIT.",
    `export const semanticTokenNames = ${JSON.stringify(roles, null, 2)} as const;`,
    "export type SemanticTokenName = (typeof semanticTokenNames)[number];",
    `export const themeNames = ${JSON.stringify(names, null, 2)} as const;`,
    "export type DesignSystemThemeName = (typeof themeNames)[number];",
    `export const themeModes = ${JSON.stringify(modes, null, 2)} as const;`,
    "export type DesignSystemThemeMode = (typeof themeModes)[number];",
    "export const semanticTokenCSSVariables: Readonly<Record<SemanticTokenName, `--ds-${string}`>> = Object.freeze({",
    ...roles.map((role) => `  ${JSON.stringify(role)}: ${JSON.stringify(cssName(role))},`),
    "});",
    "",
  ].join("\n");
}

async function current(path) {
  try { return await readFile(path, "utf8"); } catch (error) { if (error?.code === "ENOENT") return undefined; throw error; }
}

export async function generateDesignSystem(root = resolve(dirname(fileURLToPath(import.meta.url)), "../.."), { check = false } = {}) {
  const authority = await loadDesignSystem(root);
  const expected = { css: renderCSS(authority.tokens), types: renderTypes(authority.tokens) };
  const drift = [];
  for (const [key, output] of Object.entries(OUTPUTS)) {
    const path = resolve(root, output);
    if (await current(path) !== expected[key]) drift.push(output);
  }
  if (check) {
    if (drift.length) throw new Error(`DSMANIFEST_DRIFT: ${drift.sort().join(", ")}; run npm run generate:design-system`);
    return [];
  }
  for (const [key, output] of Object.entries(OUTPUTS)) {
    const path = resolve(root, output);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, expected[key], "utf8");
  }
  return drift.sort();
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const check = process.argv.slice(2).includes("--check");
  if (process.argv.slice(2).some((argument) => argument !== "--check")) throw new Error("DSMANIFEST_ARGS: only --check is supported");
  await generateDesignSystem(process.cwd(), { check });
}
