// generate.go implements API-02's OpenAPI 3.1 contract generation and its
// byte-stable, read-only drift check (07-09-PLAN.md Task 1), mirroring
// internal/contracts/generate.go's own generate+CheckDrift discipline
// (07-RESEARCH.md D-03): build the full Huma API from every currently
// self-registered operation (router.go's operationRegistrations seam),
// obtain its OpenAPI 3.1 document, serialize it byte-stably with a
// GENERATED ... DO NOT EDIT marker, and either write it to the committed
// path (GenerateOpenAPI) or compare it against the committed bytes without
// ever touching them (CheckOpenAPIDrift) -- exactly the same generate/
// CheckDrift shape internal/contracts already established, applied to this
// package's own published contract instead of a JSON Schema.
package api

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strconv"

	"github.com/danielgtaylor/huma/v2"
	"github.com/danielgtaylor/huma/v2/adapters/humachi"
	"github.com/go-chi/chi/v5"
)

// openAPIGeneratedMarker is the fixed source-of-truth marker every
// generated OpenAPI document carries, mirroring internal/contracts'
// generatedMarker convention: a reviewer must never mistake the committed
// docs/api/openapi.json for hand-authored input. Raw JSON has no comment
// syntax, so the marker is carried in two machine- and human-visible
// places: Info.Description (renders in any OpenAPI viewer/generated
// client) and the "x-generated" vendor extension (a stable, greppable
// field a tool can check without parsing prose).
const openAPIGeneratedMarker = "GENERATED by github.com/lnorton89/golc/internal/api. DO NOT EDIT."

// openAPIOutputPath is the repository-relative committed path the
// generated OpenAPI 3.1 document lives at (07-09-PLAN.md's own stated
// output-path convention, following internal/contracts' committed-path
// precedent).
const openAPIOutputPath = "docs/api/openapi.json"

// commonErrorStatuses is the fixed set of typed HTTP error statuses any
// /v1 operation can produce through this package's shared middleware and
// mutation pipeline, regardless of which specific Go code path a given
// handler's own success-path return type documents: translate.go's
// translateResult (400 malformed/unroutable, 500 domain failure), auth.go's
// AuthMiddleware (401, installed ahead of every operation in router.go's
// buildRouter) and RequireScope (403), revision.go's checkRevision /
// batch.go's own If-Match comparison (412), and ratelimit.go's
// RateLimitMiddleware (429, also installed ahead of every operation).
// Declaring all five uniformly on every generated operation documents the
// whole typed-error surface a client can encounter on ANY /v1 request --
// not just the one or two codes that specific handler's own success-path
// Go code happens to return directly -- satisfying API-02's "typed errors"
// requirement at the published-contract level (07-09-PLAN.md Task 1
// acceptance criterion: "the spec declares 400/401/403/412/429").
var commonErrorStatuses = []int{
	http.StatusBadRequest,
	http.StatusUnauthorized,
	http.StatusForbidden,
	http.StatusPreconditionFailed,
	http.StatusTooManyRequests,
}

// buildOpenAPIDocument constructs a fresh Huma API from every currently
// self-registered operation (router.go's RegisterOperation seam, the exact
// same operationRegistrations slice buildRouter iterates for a real
// *Server) and returns its OpenAPI 3.1 document. A throwaway, zero-value
// *Server is enough: every Register callback in this package only reaches
// server-specific state (executor/root/showPath/config) from inside its
// request-time handler closure, never synchronously during registration --
// the one documented exception, events.go's ensureEventStreamObserverRegistered,
// is an idempotent global-registry call safe to invoke at generation time
// (mirrors 07-08's own doc comment: "Called ... once per api.NewServer
// construction"). No HTTP listener is ever bound; auth/rate-limit
// middleware is deliberately not installed here (UseMiddleware only
// affects request handling, never the reflected operation schema Huma
// records at Register time).
func buildOpenAPIDocument() *huma.OpenAPI {
	router := chi.NewRouter()
	humaAPI := humachi.New(router, huma.DefaultConfig("GOLC API", "1.0.0"))
	generationServer := &Server{}
	for _, registration := range operationRegistrations {
		registration.Register(humaAPI, generationServer)
	}

	doc := humaAPI.OpenAPI()
	for _, pathItem := range doc.Paths {
		for _, op := range pathItemOperations(pathItem) {
			declareCommonErrors(op)
		}
	}
	if doc.Extensions == nil {
		doc.Extensions = map[string]any{}
	}
	doc.Extensions["x-generated"] = openAPIGeneratedMarker
	doc.Info.Description = openAPIGeneratedMarker
	return doc
}

// pathItemOperations returns every non-nil *huma.Operation item declares,
// across every HTTP method Huma's PathItem carries -- huma/v2 has no
// built-in "all operations on this path" accessor, so this package
// provides its own, mirroring the exact method set humachi's own router
// dispatch supports.
func pathItemOperations(item *huma.PathItem) []*huma.Operation {
	candidates := []*huma.Operation{
		item.Get, item.Put, item.Post, item.Delete,
		item.Options, item.Head, item.Patch, item.Trace,
	}
	operations := make([]*huma.Operation, 0, len(candidates))
	for _, op := range candidates {
		if op != nil {
			operations = append(operations, op)
		}
	}
	return operations
}

// declareCommonErrors adds a Responses entry for every commonErrorStatuses
// code op does not already declare (huma.Register's own defineErrors call
// may already have populated a "default" or specific-code entry for a
// route that set Operation.Errors itself; this never overwrites an
// existing entry, only fills gaps).
func declareCommonErrors(op *huma.Operation) {
	if op.Responses == nil {
		op.Responses = map[string]*huma.Response{}
	}
	for _, code := range commonErrorStatuses {
		key := strconv.Itoa(code)
		if _, exists := op.Responses[key]; exists {
			continue
		}
		op.Responses[key] = &huma.Response{Description: http.StatusText(code)}
	}
}

// renderOpenAPI builds a fresh OpenAPI document (buildOpenAPIDocument) and
// serializes it to canonical, indented JSON bytes ending in exactly one
// trailing newline -- huma.OpenAPI's own MarshalJSON already produces a
// deterministic field order and sorted map keys (encoding/json's stdlib
// guarantee for map[string]X), so no further normalization pass is needed
// (proven by TestOpenAPIDeterministic).
func renderOpenAPI() ([]byte, error) {
	doc := buildOpenAPIDocument()
	payload, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("GOLC_API_OPENAPI_MARSHAL: %v", err)
	}
	payload = append(payload, '\n')
	return payload, nil
}

// GenerateOpenAPI writes the freshly generated OpenAPI 3.1 document
// directly to its committed path under root (docs/api/openapi.json),
// mirroring internal/contracts.GenerateAll's own committed-write
// discipline.
func GenerateOpenAPI(root string) error {
	payload, err := renderOpenAPI()
	if err != nil {
		return err
	}
	destination := filepath.Join(root, filepath.FromSlash(openAPIOutputPath))
	if err := os.MkdirAll(filepath.Dir(destination), 0o755); err != nil {
		return fmt.Errorf("GOLC_API_OPENAPI_WRITE: %s: %v", openAPIOutputPath, err)
	}
	if err := os.WriteFile(destination, payload, 0o644); err != nil {
		return fmt.Errorf("GOLC_API_OPENAPI_WRITE: %s: %v", openAPIOutputPath, err)
	}
	return nil
}

// CheckOpenAPIDrift compares a freshly generated OpenAPI document against
// its committed bytes under root without ever writing anything --
// generation happens entirely in memory (renderOpenAPI), so unlike
// internal/contracts.CheckDrift this needs no disposable temp directory to
// stay strictly read-only. It returns []string{openAPIOutputPath} when the
// committed file is missing or differs, and nil when they match exactly,
// mirroring CheckDrift's own changed-paths return shape for symmetry with
// the pattern this function mirrors (internal/contracts/generate.go
// CONTEXT D-03) even though this package only ever has the one committed
// contract file.
func CheckOpenAPIDrift(root string) ([]string, error) {
	generated, err := renderOpenAPI()
	if err != nil {
		return nil, err
	}

	committedPath := filepath.Join(root, filepath.FromSlash(openAPIOutputPath))
	committed, err := os.ReadFile(committedPath)
	if err != nil {
		if os.IsNotExist(err) {
			return []string{openAPIOutputPath}, nil
		}
		return nil, fmt.Errorf("GOLC_API_OPENAPI_READ: %s: %v", openAPIOutputPath, err)
	}

	if !bytes.Equal(committed, generated) {
		return []string{openAPIOutputPath}, nil
	}
	return nil, nil
}
