package api

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/danielgtaylor/huma/v2"
)

// TestOpenAPIDeterministic proves generate.go's own byte-stable claim
// (07-09-PLAN.md Task 1 acceptance criterion): two independent generations
// against the same registered operations produce byte-identical output.
func TestOpenAPIDeterministic(t *testing.T) {
	first, err := renderOpenAPI()
	require.NoError(t, err, "renderOpenAPI (first)")
	second, err := renderOpenAPI()
	require.NoError(t, err, "renderOpenAPI (second)")
	require.Equal(t, first, second, "expected two generations to be byte-identical")
	require.NotEmpty(t, first, "expected non-empty generated output")
	require.True(t, first[len(first)-1] == '\n' && !bytes.Contains(first, []byte("\r\n")),
		"expected LF-only output ending with exactly one trailing newline, got %q", first[max(0, len(first)-20):])
}

// TestOpenAPIDrift proves CheckOpenAPIDrift's own read-only, never-
// rewrites-committed-bytes claim: it reports drift for a missing committed
// file, reports no drift once the exact generated bytes are written, and
// never itself creates or modifies the committed file.
func TestOpenAPIDrift(t *testing.T) {
	root := t.TempDir()

	changed, err := CheckOpenAPIDrift(root)
	require.NoError(t, err, "CheckOpenAPIDrift (missing file)")
	require.Equal(t, []string{openAPIOutputPath}, changed, "expected drift for a never-committed %s", openAPIOutputPath)
	_, statErr := os.Stat(filepath.Join(root, filepath.FromSlash(openAPIOutputPath)))
	require.Error(t, statErr, "CheckOpenAPIDrift must never write the committed file, but it now exists")

	require.NoError(t, GenerateOpenAPI(root), "GenerateOpenAPI")

	changed, err = CheckOpenAPIDrift(root)
	require.NoError(t, err, "CheckOpenAPIDrift (in sync)")
	require.Empty(t, changed, "expected no drift immediately after GenerateOpenAPI")

	// Corrupt the committed file and confirm drift is detected again,
	// without CheckOpenAPIDrift silently repairing it.
	committedPath := filepath.Join(root, filepath.FromSlash(openAPIOutputPath))
	require.NoError(t, os.WriteFile(committedPath, []byte("{}\n"), 0o644), "corrupt committed file")
	changed, err = CheckOpenAPIDrift(root)
	require.NoError(t, err, "CheckOpenAPIDrift (drifted)")
	require.Equal(t, []string{openAPIOutputPath}, changed, "expected drift after corrupting the committed file")
	corrupted, readErr := os.ReadFile(committedPath)
	require.NoError(t, readErr, "read corrupted file back")
	require.Equal(t, "{}\n", string(corrupted), "CheckOpenAPIDrift must never rewrite the committed file even when it drifted")
}

// TestOpenAPIDocumentsEveryOperation proves the generated document covers
// every /v1 operation currently self-registered (queries, mutations,
// batch, keys) plus the typed error responses this package's shared
// middleware/mutation pipeline can produce on any request.
func TestOpenAPIDocumentsEveryOperation(t *testing.T) {
	doc := buildOpenAPIDocument()

	require.NotEmpty(t, operationRegistrations, "expected at least one self-registered operation to generate against")
	require.NotEmpty(t, doc.Paths, "expected the generated document to declare at least one path")

	wantPaths := []string{
		apiPathPrefix + "/config/{concern}",
		apiPathPrefix + "/show",
		apiPathPrefix + "/pools",
		apiPathPrefix + "/batch",
		apiPathPrefix + "/keys",
		apiPathPrefix + "/events",
	}
	for _, path := range wantPaths {
		assert.Contains(t, doc.Paths, path, "expected the generated document to declare path %q, got paths: %v", path, pathKeys(doc.Paths))
	}

	wantErrorCodes := []string{"400", "401", "403", "412", "429"}
	for path, item := range doc.Paths {
		for _, op := range pathItemOperations(item) {
			for _, code := range wantErrorCodes {
				assert.Contains(t, op.Responses, code, "expected operation %q (%s) to declare a %s response, got responses: %v",
					op.OperationID, path, code, responseKeys(op.Responses))
			}
		}
	}
}

// TestOpenAPIGeneratedMarker proves the committed document is
// self-identifying as generated (never mistaken for hand-authored input).
func TestOpenAPIGeneratedMarker(t *testing.T) {
	doc := buildOpenAPIDocument()
	require.Equal(t, openAPIGeneratedMarker, doc.Extensions["x-generated"])
	require.Equal(t, openAPIGeneratedMarker, doc.Info.Description)

	payload, err := renderOpenAPI()
	require.NoError(t, err, "renderOpenAPI")
	var decoded map[string]any
	require.NoError(t, json.Unmarshal(payload, &decoded), "expected valid JSON output")
	require.Equal(t, openAPIGeneratedMarker, decoded["x-generated"])
	require.NotNil(t, decoded["openapi"], "expected a top-level \"openapi\" version field (OpenAPI 3.1 document)")
}

func pathKeys(paths map[string]*huma.PathItem) []string {
	keys := make([]string, 0, len(paths))
	for k := range paths {
		keys = append(keys, k)
	}
	return keys
}

func responseKeys(responses map[string]*huma.Response) []string {
	keys := make([]string, 0, len(responses))
	for k := range responses {
		keys = append(keys, k)
	}
	return keys
}
