// generate.go implements the deterministic, drift-checked typed GOLC SDK
// generator (08-03-PLAN.md Task 1, CONTEXT SCRP-02): a self-registering
// descriptor registry mirroring internal/contracts/generate.go's exact
// generation discipline (SchemaDescriptor/MustRegisterSchema/GenerateInto/
// CheckDrift), but emitting two committed TypeScript artifacts instead of
// one JSON Schema per descriptor:
//
//   - golc.d.ts: ambient global types (`declare namespace golc { ... }`)
//     Monaco's TypeScript language service loads for live autocomplete
//     (08-11). It contains no `import` or `export` statement anywhere, so a
//     user script has no module specifier for Deno's resolver to ever fetch
//     (08-RESEARCH.md Pitfall 4).
//   - golc-runtime.ts: the newline-delimited-JSON stdio client the
//     sandboxed Deno process runs, populated with real functions generated
//     from the exact same descriptor list -- the types and the runtime
//     shim can never diverge because both render from one registry.
//
// internal/scriptsdk never imports internal/command (see descriptors.go's
// package comment): the route-string agreement between this registry and
// the real command registry is asserted by an external parity test,
// internal/command/scriptsdk_parity_test.go (08-03-PLAN.md Task 3), not by
// an import cycle.
package scriptsdk

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"sync"

	"github.com/invopop/jsonschema"

	"github.com/lnorton89/golc/internal/show"
)

// generatedMarker is the fixed source-of-truth comment every generated SDK
// file carries (mirrors internal/contracts' generatedMarker convention):
// generated bytes always name their producer so a reviewer never mistakes
// them for hand-authored input.
const generatedMarker = "GENERATED by github.com/lnorton89/golc/internal/scriptsdk. DO NOT EDIT."

// generatedDir is the committed repository-relative directory both
// generated files live under.
const generatedDir = "internal/scriptsdk/generated"

// typesOutputPath and runtimeOutputPath are the two committed generated
// file paths GenerateInto/GenerateAll/CheckDrift operate on.
const (
	typesOutputPath   = generatedDir + "/golc.d.ts"
	runtimeOutputPath = generatedDir + "/golc-runtime.ts"
)

// SDKMethodDescriptor is one typed GOLC SDK method: a real internal/command
// route this SDK exposes to scripts, the generated TypeScript method
// dot-path it renders as, and the required.APIKeyScope the host must
// enforce for every call to it (D-06).
type SDKMethodDescriptor struct {
	// Route is the exact normalized command route this method calls, for
	// example "scene activate" -- must match a route internal/command's
	// registry actually declares (asserted by the external parity test).
	Route string
	// Method is the generated TypeScript method dot-path, for example
	// "scene.activate": each dot-separated segment becomes one level of
	// nested `namespace` in golc.d.ts and one level of nested object in
	// golc-runtime.ts.
	Method string
	// Summary is a one-line human-readable description of the method,
	// rendered as a leading TSDoc comment above its declaration.
	Summary string
	// Scope is the show.APIKeyScope this method's underlying route
	// requires -- the single source of truth 08-06's host-side enforcement
	// reads from, never a hand-maintained second list.
	Scope show.APIKeyScope
	// Params is a zero-value Go struct reflected via jsonschema into the
	// method's generated TypeScript Params interface. Every field must map
	// onto a real flag the underlying route accepts -- this registry never
	// invents an argument the command itself does not have.
	Params any
	// Result is a zero-value Go struct reflected via jsonschema into the
	// method's generated TypeScript Result interface (the type behind the
	// returned Promise).
	Result any
}

// registry is the package-level compile-safe SDK method registry, guarded
// by mutex the same way internal/contracts' registry is (RegisterSchema's
// doc comment) even though today's self-registration only ever runs during
// single-goroutine package initialization -- the mutex keeps the contract
// explicit and future-proof against a caller registering after init.
var registry = struct {
	mu      sync.Mutex
	byRoute map[string]SDKMethodDescriptor
}{
	byRoute: map[string]SDKMethodDescriptor{},
}

// excludedRoutes is every declared command route deliberately NOT exposed
// to scripts, mapped to a one-line reason (populated in descriptors.go,
// Task 2). RegisterExclusion is the only mutator; RegisteredExclusions
// returns a defensive copy.
var excludedRoutes = struct {
	mu      sync.Mutex
	reasons map[string]string
}{
	reasons: map[string]string{},
}

// RegisterSDKMethod adds one descriptor to the package-level registry. It
// rejects a descriptor missing Route, Method, or Scope
// (GOLC_SCRIPTSDK_DESCRIPTOR_INVALID) and a Route already registered
// (GOLC_SCRIPTSDK_ROUTE_DUPLICATE).
func RegisterSDKMethod(descriptor SDKMethodDescriptor) error {
	route := strings.TrimSpace(descriptor.Route)
	method := strings.TrimSpace(descriptor.Method)
	if route == "" || method == "" || descriptor.Scope == "" {
		return fmt.Errorf(
			"GOLC_SCRIPTSDK_DESCRIPTOR_INVALID: descriptor %+v is missing Route, Method, or Scope", descriptor)
	}

	registry.mu.Lock()
	defer registry.mu.Unlock()
	if _, exists := registry.byRoute[route]; exists {
		return fmt.Errorf("GOLC_SCRIPTSDK_ROUTE_DUPLICATE: route %q is already registered", route)
	}
	descriptor.Route = route
	descriptor.Method = method
	registry.byRoute[route] = descriptor
	return nil
}

// MustRegisterSDKMethod is the compile-safe self-registration entrypoint
// descriptors.go calls from a package-level var initializer:
//
//	var _ = scriptsdk.MustRegisterSDKMethod(scriptsdk.SDKMethodDescriptor{...})
//
// A rejected registration panics immediately at program startup rather than
// surfacing as a later, harder to diagnose generation failure.
func MustRegisterSDKMethod(descriptor SDKMethodDescriptor) SDKMethodDescriptor {
	if err := RegisterSDKMethod(descriptor); err != nil {
		panic(err.Error())
	}
	return descriptor
}

// RegisterExclusion adds one deliberately-excluded route with its one-line
// reason. It rejects a blank route or reason (GOLC_SCRIPTSDK_DESCRIPTOR_INVALID)
// and a route already excluded (GOLC_SCRIPTSDK_ROUTE_DUPLICATE) -- the same
// two diagnostics RegisterSDKMethod uses, since both are the same
// "route already classified" failure mode from a contributor's perspective.
// RegisterSDKMethod and RegisterExclusion share one Route namespace: a
// route registered as an SDK method cannot also be excluded, and vice versa.
func RegisterExclusion(route, reason string) error {
	trimmedRoute := strings.TrimSpace(route)
	trimmedReason := strings.TrimSpace(reason)
	if trimmedRoute == "" || trimmedReason == "" {
		return fmt.Errorf("GOLC_SCRIPTSDK_DESCRIPTOR_INVALID: exclusion route/reason must not be blank")
	}

	registry.mu.Lock()
	_, exposed := registry.byRoute[trimmedRoute]
	registry.mu.Unlock()
	if exposed {
		return fmt.Errorf("GOLC_SCRIPTSDK_ROUTE_DUPLICATE: route %q is both exposed and excluded", trimmedRoute)
	}

	excludedRoutes.mu.Lock()
	defer excludedRoutes.mu.Unlock()
	if _, exists := excludedRoutes.reasons[trimmedRoute]; exists {
		return fmt.Errorf("GOLC_SCRIPTSDK_ROUTE_DUPLICATE: route %q is already excluded", trimmedRoute)
	}
	excludedRoutes.reasons[trimmedRoute] = trimmedReason
	return nil
}

// MustRegisterExclusion is RegisterExclusion's compile-safe self-registration
// entrypoint, mirroring MustRegisterSDKMethod.
func MustRegisterExclusion(route, reason string) string {
	if err := RegisterExclusion(route, reason); err != nil {
		panic(err.Error())
	}
	return route
}

// RegisteredSDKMethods returns every registered descriptor as a defensive
// snapshot sorted by Route: mutating the returned slice never affects the
// package-level registry, and repeated calls made without an intervening
// registration are byte-identical in order.
func RegisteredSDKMethods() []SDKMethodDescriptor {
	registry.mu.Lock()
	defer registry.mu.Unlock()

	routes := make([]string, 0, len(registry.byRoute))
	for route := range registry.byRoute {
		routes = append(routes, route)
	}
	sort.Strings(routes)

	snapshot := make([]SDKMethodDescriptor, 0, len(routes))
	for _, route := range routes {
		snapshot = append(snapshot, registry.byRoute[route])
	}
	return snapshot
}

// RegisteredExclusions returns a defensive copy of every excluded route's
// reason.
func RegisteredExclusions() map[string]string {
	excludedRoutes.mu.Lock()
	defer excludedRoutes.mu.Unlock()

	copyOf := make(map[string]string, len(excludedRoutes.reasons))
	for route, reason := range excludedRoutes.reasons {
		copyOf[route] = reason
	}
	return copyOf
}

// reflector is the one jsonschema.Reflector configuration every Params/
// Result type in this package reflects through: Draft 2020-12 by default,
// and DoNotReference so every reflected struct is self-contained -- every
// Params/Result type this package declares is intentionally flat (no
// nested struct fields), so there is never a nested type worth extracting
// into a shared $defs entry.
func reflector() *jsonschema.Reflector {
	return &jsonschema.Reflector{DoNotReference: true}
}

// reflectShape reflects value's Go type into a jsonschema.Schema. value
// must be a zero-value struct (never a pointer) -- every SDKMethodDescriptor
// in descriptors.go supplies its Params/Result this way.
func reflectShape(value any) *jsonschema.Schema {
	return reflector().Reflect(value)
}

// goTypeName returns value's underlying Go struct type name (e.g.
// "PoolCreateParams" for a scriptsdk.PoolCreateParams{} value) -- the
// interface name renderTypes emits and renderRuntime references.
func goTypeName(value any) string {
	t := reflect.TypeOf(value)
	for t.Kind() == reflect.Ptr {
		t = t.Elem()
	}
	return t.Name()
}

// sortedKeys returns m's keys in stable lexicographic order -- shared by
// every map-keyed renderer in this file so traversal order never depends on
// Go's randomized map iteration.
func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for key := range m {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

// collectInterfaces reflects every distinct Params/Result Go type across
// descriptors exactly once, keyed by its Go type name, so a type shared by
// more than one descriptor (for example a common "<name> --show <path>"
// shape) still renders exactly one committed TypeScript interface.
func collectInterfaces(descriptors []SDKMethodDescriptor) map[string]*jsonschema.Schema {
	interfaces := map[string]*jsonschema.Schema{}
	for _, descriptor := range descriptors {
		for _, value := range []any{descriptor.Params, descriptor.Result} {
			name := goTypeName(value)
			if _, exists := interfaces[name]; exists {
				continue
			}
			interfaces[name] = reflectShape(value)
		}
	}
	return interfaces
}

// lowerScalar renders one jsonschema property schema as its TypeScript
// type: the closed, deliberately small set of shapes every Params/Result
// field in this package uses (string, number, boolean, and an Array of one
// of those). Any other shape is a programmer error in this package's own
// type declarations, not a runtime possibility -- it renders "unknown"
// rather than panicking, so a malformed descriptor fails loudly via a
// mismatched golc.d.ts rather than crashing generation.
func lowerScalar(schema *jsonschema.Schema) string {
	switch schema.Type {
	case "string":
		return "string"
	case "integer", "number":
		return "number"
	case "boolean":
		return "boolean"
	case "array":
		if schema.Items != nil {
			return "Array<" + lowerScalar(schema.Items) + ">"
		}
		return "Array<unknown>"
	default:
		return "unknown"
	}
}

// renderInterface writes one export-free TypeScript interface declaration
// for name/schema: required fields (schema.Required) render without a "?",
// every other field renders optional.
func renderInterface(name string, schema *jsonschema.Schema, out *strings.Builder) {
	required := map[string]bool{}
	for _, field := range schema.Required {
		required[field] = true
	}

	fmt.Fprintf(out, "interface %s {\n", name)
	if schema.Properties != nil {
		for fieldName, fieldSchema := range schema.Properties.FromOldest() {
			optional := "?"
			if required[fieldName] {
				optional = ""
			}
			fmt.Fprintf(out, "  %s%s: %s;\n", fieldName, optional, lowerScalar(fieldSchema))
		}
	}
	out.WriteString("}\n")
}

// namespaceNode is one level of the nested namespace/object tree
// buildNamespaceTree constructs from every descriptor's dot-separated
// Method path: renderNamespaceTypes (golc.d.ts) and renderNamespaceRuntime
// (golc-runtime.ts) both walk the identical tree, so the two files can
// never declare a different method set.
type namespaceNode struct {
	children map[string]*namespaceNode
	methods  map[string]SDKMethodDescriptor
}

func newNamespaceNode() *namespaceNode {
	return &namespaceNode{children: map[string]*namespaceNode{}, methods: map[string]SDKMethodDescriptor{}}
}

// buildNamespaceTree groups descriptors by their Method dot-path: every
// segment before the last becomes one level of nested namespace/object, and
// the last segment becomes one leaf method.
func buildNamespaceTree(descriptors []SDKMethodDescriptor) *namespaceNode {
	root := newNamespaceNode()
	for _, descriptor := range descriptors {
		segments := strings.Split(descriptor.Method, ".")
		node := root
		for _, segment := range segments[:len(segments)-1] {
			child, exists := node.children[segment]
			if !exists {
				child = newNamespaceNode()
				node.children[segment] = child
			}
			node = child
		}
		node.methods[segments[len(segments)-1]] = descriptor
	}
	return root
}

// renderNamespaceTypes recursively renders node as golc.d.ts content: every
// leaf method as an ambient function signature, every child as a nested
// `namespace`. Traversal order is always the sorted key order sortedKeys
// returns, so output is byte-stable regardless of registration order.
func renderNamespaceTypes(node *namespaceNode, indent string, out *strings.Builder) {
	for _, name := range sortedKeys(node.methods) {
		descriptor := node.methods[name]
		fmt.Fprintf(out, "%s// %s (scope: %s)\n", indent, descriptor.Summary, descriptor.Scope)
		fmt.Fprintf(out, "%sfunction %s(params: %s): Promise<%s>;\n",
			indent, name, goTypeName(descriptor.Params), goTypeName(descriptor.Result))
	}
	for _, name := range sortedKeys(node.children) {
		fmt.Fprintf(out, "%snamespace %s {\n", indent, name)
		renderNamespaceTypes(node.children[name], indent+"  ", out)
		fmt.Fprintf(out, "%s}\n", indent)
	}
}

// renderNamespaceRuntime recursively renders node as a golc-runtime.ts
// object-literal fragment: every leaf method as an arrow function that
// marshals a {kind:"cmd-call", id, method, params} frame over stdio
// (internal/script/protocol.go's CmdCallFrame, 08-05) and awaits its
// matching response, every child as a nested object literal.
func renderNamespaceRuntime(node *namespaceNode, indent string, out *strings.Builder) {
	names := append(append([]string{}, sortedKeys(node.methods)...), sortedKeys(node.children)...)
	sort.Strings(names)
	for i, name := range names {
		trailingComma := ","
		if i == len(names)-1 {
			trailingComma = ""
		}
		if descriptor, isMethod := node.methods[name]; isMethod {
			fmt.Fprintf(out, "%s%s: (params: any): Promise<any> => __golcCall(%q, params)%s\n",
				indent, name, descriptor.Route, trailingComma)
			continue
		}
		fmt.Fprintf(out, "%s%s: {\n", indent, name)
		renderNamespaceRuntime(node.children[name], indent+"  ", out)
		fmt.Fprintf(out, "%s}%s\n", indent, trailingComma)
	}
}

// runtimeTransportPrelude is the newline-delimited-JSON stdio request/
// response client every generated golc-runtime.ts commits verbatim: a
// monotonically increasing request id (stringified) correlates each
// {kind:"cmd-call", id, method, params} frame written to stdout with its
// {kind:"cmd-result", id, ok, result}/{kind:"cmd-result", id, ok:false,
// code, message} response read from stdin -- internal/script/protocol.go's
// CmdCallFrame/CmdResultFrame shape exactly (08-05: the Go decoder and
// this generated shim must agree byte-for-byte on the wire frame shape).
// It never uses an import or export statement -- the shim is injected by
// the host alongside the user's zero-import script (08-05), and assigns
// itself onto globalThis exactly like the ambient golc.d.ts types
// describe.
const runtimeTransportPrelude = `const __golcEncoder = new TextEncoder();
const __golcDecoder = new TextDecoder();

// console.* is redirected to Deno.stderr, never left on Deno.stdout: stdout
// is reserved exclusively for this file's own strict newline-delimited JSON
// protocol frames (cmd-call/cmd-result/done), and the host's frame decoder
// treats any non-JSON stdout line as a fatal protocol violation. A script's
// ordinary console.log/info/warn/error/debug calls are still the natural
// way to produce D-04's live log stream -- they are just carried over the
// same stderr channel the host already redacts and captures as log lines
// (session.go's runDispatchIO), never mixed into the control channel.
function __golcWriteConsoleLine(args: unknown[]): void {
  const text = args
    .map((a) => (typeof a === "string" ? a : (globalThis as any).Deno.inspect(a)))
    .join(" ");
  (globalThis as any).Deno.stderr.writeSync(__golcEncoder.encode(text + "\n"));
}
for (const __golcMethod of ["log", "info", "warn", "error", "debug"] as const) {
  (globalThis as any).console[__golcMethod] = (...args: unknown[]) => __golcWriteConsoleLine(args);
}

let __golcRequestID = 0;
const __golcPending = new Map<string, { resolve: (value: any) => void; reject: (reason: any) => void }>();
let __golcReaderStarted = false;

function __golcStartReader(): void {
  if (__golcReaderStarted) {
    return;
  }
  __golcReaderStarted = true;
  (async () => {
    let buffer = "";
    for await (const chunk of (globalThis as any).Deno.stdin.readable) {
      buffer += __golcDecoder.decode(chunk, { stream: true });
      let newlineIndex: number;
      while ((newlineIndex = buffer.indexOf("\n")) >= 0) {
        const line = buffer.slice(0, newlineIndex);
        buffer = buffer.slice(newlineIndex + 1);
        if (line.length === 0) {
          continue;
        }
        const frame = JSON.parse(line);
        if (frame.kind !== "cmd-result") {
          continue;
        }
        const pending = __golcPending.get(frame.id);
        if (!pending) {
          continue;
        }
        __golcPending.delete(frame.id);
        if (frame.ok) {
          pending.resolve(frame.result);
        } else {
          pending.reject(new Error(frame.code + ": " + frame.message));
        }
      }
    }
  })();
}

function __golcCall(method: string, params: unknown): Promise<any> {
  __golcStartReader();
  const id = String(++__golcRequestID);
  const line = JSON.stringify({ kind: "cmd-call", id, method, params }) + "\n";
  return (globalThis as any).Deno.stdout.write(__golcEncoder.encode(line)).then(() => {
    return new Promise((resolve, reject) => {
      __golcPending.set(id, { resolve, reject });
    });
  });
}

`

// renderTypes emits golc.d.ts: the generated marker, one export-free
// interface per distinct Params/Result Go type (sorted by name), and a
// single ambient `declare namespace golc { ... }` block whose nested
// namespaces mirror every descriptor's Method dot-path. It never emits an
// `import` or `export` keyword (08-RESEARCH.md Pitfall 4): a user script
// has no legitimate module specifier for Deno's resolver to ever see.
func renderTypes() ([]byte, error) {
	descriptors := RegisteredSDKMethods()
	interfaces := collectInterfaces(descriptors)

	var out strings.Builder
	fmt.Fprintf(&out, "// %s\n", generatedMarker)
	out.WriteString("// golc.d.ts: ambient global GOLC SDK types for the in-app Monaco editor (D-15).\n")
	out.WriteString("// This file declares no import and no export -- see 08-RESEARCH.md Pitfall 4:\n")
	out.WriteString("// a user script must never have a module specifier for Deno's resolver to see.\n\n")

	for _, name := range sortedKeys(interfaces) {
		renderInterface(name, interfaces[name], &out)
		out.WriteString("\n")
	}

	out.WriteString("declare namespace golc {\n")
	renderNamespaceTypes(buildNamespaceTree(descriptors), "  ", &out)
	out.WriteString("}\n")

	return normalizeLF([]byte(out.String())), nil
}

// renderRuntime emits golc-runtime.ts: the generated marker,
// runtimeTransportPrelude's stdio JSON-lines client, and the same golc
// namespace shape as golc.d.ts, but populated with real functions -- every
// leaf function is generated from the identical descriptor list renderTypes
// uses, so the runtime and the types can never diverge.
func renderRuntime() ([]byte, error) {
	descriptors := RegisteredSDKMethods()

	var out strings.Builder
	fmt.Fprintf(&out, "// %s\n", generatedMarker)
	out.WriteString("// golc-runtime.ts: stdio JSON-lines client injected by the host (08-05) alongside\n")
	out.WriteString("// the sandboxed user script. This file declares no import and no export either --\n")
	out.WriteString("// it assigns itself onto globalThis exactly like golc.d.ts's ambient types describe.\n\n")

	out.WriteString(runtimeTransportPrelude)

	out.WriteString("(globalThis as any).golc = {\n")
	renderNamespaceRuntime(buildNamespaceTree(descriptors), "  ", &out)
	out.WriteString("};\n")

	return normalizeLF([]byte(out.String())), nil
}

// normalizeLF strips carriage returns and ensures data ends with exactly
// one trailing LF byte, mirroring internal/contracts.NormalizeLF -- Windows
// and CI must produce byte-identical committed output regardless of the
// host's native line ending.
func normalizeLF(data []byte) []byte {
	normalized := bytes.ReplaceAll(data, []byte("\r\n"), []byte("\n"))
	normalized = bytes.TrimRight(normalized, "\n")
	normalized = append(normalized, '\n')
	return normalized
}

// GenerateInto writes golc.d.ts and golc-runtime.ts under targetRoot
// instead of the committed repository root, so a caller (including
// CheckDrift) can generate into a disposable directory without ever
// touching committed bytes.
func GenerateInto(targetRoot string) error {
	typesBytes, err := renderTypes()
	if err != nil {
		return fmt.Errorf("GOLC_SCRIPTSDK_RENDER_FAILED: %v", err)
	}
	runtimeBytes, err := renderRuntime()
	if err != nil {
		return fmt.Errorf("GOLC_SCRIPTSDK_RENDER_FAILED: %v", err)
	}

	for _, write := range []struct {
		path    string
		content []byte
	}{
		{typesOutputPath, typesBytes},
		{runtimeOutputPath, runtimeBytes},
	} {
		destination := filepath.Join(targetRoot, filepath.FromSlash(write.path))
		if err := os.MkdirAll(filepath.Dir(destination), 0o755); err != nil {
			return fmt.Errorf("GOLC_SCRIPTSDK_RENDER_FAILED: %s: %v", write.path, err)
		}
		if err := os.WriteFile(destination, write.content, 0o644); err != nil {
			return fmt.Errorf("GOLC_SCRIPTSDK_RENDER_FAILED: %s: %v", write.path, err)
		}
	}
	return nil
}

// GenerateAll regenerates golc.d.ts and golc-runtime.ts directly at their
// committed repository-relative paths under root -- the entrypoint
// internal/command/generate.go wires up alongside contracts.GenerateAll.
func GenerateAll(root string) error {
	return GenerateInto(root)
}

// CheckDrift compares freshly generated bytes against the committed
// golc.d.ts/golc-runtime.ts without ever writing to the committed location:
// generation happens once into a disposable temporary directory, and only
// that directory's output is read back for comparison. It returns the
// changed committed paths (including a file that does not exist yet) in
// stable sorted order.
func CheckDrift(root string) ([]string, error) {
	tempDir, err := os.MkdirTemp("", "golc-scriptsdk-check-*")
	if err != nil {
		return nil, fmt.Errorf("GOLC_SCRIPTSDK_DRIFT: %v", err)
	}
	defer os.RemoveAll(tempDir)

	if err := GenerateInto(tempDir); err != nil {
		return nil, err
	}

	changed := []string{}
	for _, path := range []string{typesOutputPath, runtimeOutputPath} {
		generatedBytes, err := os.ReadFile(filepath.Join(tempDir, filepath.FromSlash(path)))
		if err != nil {
			return nil, fmt.Errorf("GOLC_SCRIPTSDK_DRIFT: %s: %v", path, err)
		}

		committedPath := filepath.Join(root, filepath.FromSlash(path))
		committedBytes, err := os.ReadFile(committedPath)
		if err != nil {
			if os.IsNotExist(err) {
				changed = append(changed, path)
				continue
			}
			return nil, fmt.Errorf("GOLC_SCRIPTSDK_DRIFT: %s: %v", path, err)
		}

		if !bytes.Equal(committedBytes, generatedBytes) {
			changed = append(changed, path)
		}
	}
	sort.Strings(changed)
	return changed, nil
}
