// Package docgen extracts each internal package's godoc-style package
// comment and renders it as a standalone Markdown reference page.
//
// Discovery walks internal/ on disk rather than using a manual registry
// (contrast internal/contracts's MustRegisterSchema pattern): package
// documentation already lives at a fixed, discoverable location (the
// leading "// Package x ..." comment on some file in the directory), so a
// later package becomes part of GenerateAll the moment its own doc
// comment exists, without any registration call anywhere. A directory
// with no package-level doc comment is silently skipped (not every
// internal package documents itself yet), and directories whose only Go
// files are test files (external "foo_test" packages) are never
// considered, so committed pages only ever describe production code.
package docgen

import (
	"fmt"
	"go/doc"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// modulePath is the GOLC module path every discovered import path is
// built from (matches go.mod exactly).
const modulePath = "github.com/lnorton89/golc"

// generatedMarker is the fixed source-of-truth comment every generated
// page and the index carry (mirrors internal/contracts's generatedMarker
// convention so a reviewer never mistakes either for hand-authored
// input).
const generatedMarker = "<!-- GENERATED by github.com/lnorton89/golc/internal/docgen. DO NOT EDIT. -->"

// ReferenceDocsDir is the committed repository-relative directory each
// page (and the generated index) is written under.
const ReferenceDocsDir = "docs/reference"

// SiteReferenceDir is the golc-site submodule's repository-relative
// content directory the same pages are copied into, so the marketing
// site's docs page can render them without depending on golc's own docs/
// tree at build time — golc-site is a separate git repository checked
// out at ./site, and its Netlify build never sees anything outside it.
const SiteReferenceDir = "site/src/content/reference"

// Page is one discovered package's rendered reference page.
type Page struct {
	// ImportPath is the full Go import path, e.g.
	// "github.com/lnorton89/golc/internal/bootstrap".
	ImportPath string
	// Slug is the stable, filesystem- and URL-safe identifier derived
	// from ImportPath (the portion after the module path, with "/"
	// replaced by "-"), e.g. "bootstrap" or "trace-apply".
	Slug string
	// Name is the Go package name, e.g. "bootstrap".
	Name string
	// Synopsis is the package doc comment's first sentence.
	Synopsis string
	// Body is the full rendered Markdown page, including the generated
	// marker, heading, import path, and complete doc comment.
	Body []byte
}

// Discover walks root/internal and returns one Page per directory that
// has at least one non-test .go file whose package carries a
// package-level doc comment, sorted by ImportPath.
func Discover(root string) ([]Page, error) {
	internalDir := filepath.Join(root, "internal")

	var dirs []string
	walkErr := filepath.Walk(internalDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			dirs = append(dirs, path)
		}
		return nil
	})
	if walkErr != nil {
		return nil, fmt.Errorf("GOLC_DOCGEN_WALK: %v", walkErr)
	}
	sort.Strings(dirs)

	fset := token.NewFileSet()
	var pages []Page
	for _, dir := range dirs {
		page, ok, err := packagePage(fset, root, dir)
		if err != nil {
			return nil, err
		}
		if ok {
			pages = append(pages, page)
		}
	}
	sort.Slice(pages, func(i, j int) bool { return pages[i].ImportPath < pages[j].ImportPath })
	return pages, nil
}

// packagePage parses one directory's production (non-test) Go files and
// renders a Page from its package doc comment. The second return value
// is false (with a nil error) whenever the directory has no production
// Go files or no file's leading comment is an actual package doc comment
// — both are ordinary, silent skips, not failures.
//
// Only the one file whose leading comment starts with "Package " (by Go
// convention, exactly one file per package — e.g. bootstrap.go's
// "Package bootstrap implements ...") is used. go/doc's own
// NewFromFiles/New concatenate every file's leading comment into Doc,
// which is right for godoc's own rendering but wrong here: this
// repository's own convention (CONTEXT D-03's command-file doc comments,
// for example) gives every file a leading comment explaining what that
// file does, and only the genuine package summary belongs on its
// reference page.
func packagePage(fset *token.FileSet, root, dir string) (Page, bool, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return Page{}, false, fmt.Errorf("GOLC_DOCGEN_READDIR: %s: %v", dir, err)
	}

	var packageName, packageDoc string
	sawProductionFile := false
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		sawProductionFile = true

		fullPath := filepath.Join(dir, name)
		parsed, err := parser.ParseFile(fset, fullPath, nil, parser.ParseComments)
		if err != nil {
			return Page{}, false, fmt.Errorf("GOLC_DOCGEN_PARSE: %s: %v", fullPath, err)
		}
		packageName = parsed.Name.Name

		if packageDoc != "" || parsed.Doc == nil {
			continue
		}
		if text := parsed.Doc.Text(); strings.HasPrefix(text, "Package ") {
			packageDoc = text
		}
	}
	if !sawProductionFile || strings.TrimSpace(packageDoc) == "" {
		return Page{}, false, nil
	}

	relDir, err := filepath.Rel(root, dir)
	if err != nil {
		return Page{}, false, fmt.Errorf("GOLC_DOCGEN_RELPATH: %s: %v", dir, err)
	}
	importPath := modulePath + "/" + filepath.ToSlash(relDir)
	sluggable := strings.TrimPrefix(filepath.ToSlash(relDir), "internal/")
	slug := strings.ReplaceAll(sluggable, "/", "-")

	return Page{
		ImportPath: importPath,
		Slug:       slug,
		Name:       packageName,
		Synopsis:   doc.Synopsis(packageDoc),
		Body:       renderPage(packageName, importPath, packageDoc),
	}, true, nil
}

// renderPage builds one package's complete Markdown page: the generated
// marker, a level-1 heading naming the package, its import path in a
// code span, and the full doc comment verbatim.
func renderPage(name, importPath, comment string) []byte {
	var b strings.Builder
	b.WriteString(generatedMarker)
	b.WriteString("\n# ")
	b.WriteString(name)
	b.WriteString("\n\n`")
	b.WriteString(importPath)
	b.WriteString("`\n\n")
	b.WriteString(strings.TrimRight(comment, "\n"))
	b.WriteString("\n")
	return []byte(b.String())
}

// renderIndex builds the committed docs/reference/README.md contents
// index-linking every page in the same ImportPath-sorted order Discover
// returns.
func renderIndex(pages []Page) []byte {
	var b strings.Builder
	b.WriteString(generatedMarker)
	b.WriteString("\n# Package reference\n\n")
	b.WriteString("One page per internal package that carries a package-level doc comment, generated by `golc.ps1 docs` (internal/docgen).\n\n")
	for _, page := range pages {
		fmt.Fprintf(&b, "- [%s](./%s.md) — %s\n", page.ImportPath, page.Slug, page.Synopsis)
	}
	return []byte(b.String())
}

// GenerateAll discovers every documented internal package under root and
// writes its rendered page to both ReferenceDocsDir and SiteReferenceDir,
// plus a generated index at ReferenceDocsDir/README.md. Every write
// target is created fresh from the current source on every call, so
// removing a package's doc comment (or the package itself) removes its
// page on the next run. It returns the pages written, sorted by
// ImportPath.
func GenerateAll(root string) ([]Page, error) {
	pages, err := Discover(root)
	if err != nil {
		return nil, err
	}

	for _, dir := range [...]string{ReferenceDocsDir, SiteReferenceDir} {
		targetDir := filepath.Join(root, filepath.FromSlash(dir))
		if err := resetDir(targetDir); err != nil {
			return nil, fmt.Errorf("GOLC_DOCGEN_RESET: %s: %v", dir, err)
		}
		for _, page := range pages {
			destination := filepath.Join(targetDir, page.Slug+".md")
			if err := os.WriteFile(destination, page.Body, 0o644); err != nil {
				return nil, fmt.Errorf("GOLC_DOCGEN_WRITE: %s: %v", destination, err)
			}
		}
	}

	indexPath := filepath.Join(root, filepath.FromSlash(ReferenceDocsDir), "README.md")
	if err := os.WriteFile(indexPath, renderIndex(pages), 0o644); err != nil {
		return nil, fmt.Errorf("GOLC_DOCGEN_WRITE: %s: %v", indexPath, err)
	}

	return pages, nil
}

// resetDir replaces targetDir's Markdown page contents with an empty,
// freshly created directory: a page for a package that no longer exists
// (or no longer has a doc comment) must not linger from a previous run.
func resetDir(targetDir string) error {
	entries, err := os.ReadDir(targetDir)
	if err != nil {
		if os.IsNotExist(err) {
			return os.MkdirAll(targetDir, 0o755)
		}
		return err
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".md") {
			continue
		}
		if err := os.Remove(filepath.Join(targetDir, entry.Name())); err != nil {
			return err
		}
	}
	return nil
}
