// reference_property_test.go property-tests decode.go's typed
// cross-concern reference resolver (resolveReference, exercised through
// the exported ValidateRepository) against arbitrary reference graphs
// generated by pgregory.net/rapid: acyclic chains of any depth or fan-in
// resolve to their terminal literal, any cycle (including a one-node
// self-reference) fails with GOLC_CONFIG_REF_CYCLE, and any reference to
// an undeclared key fails with GOLC_CONFIG_REF_UNRESOLVED.
// strict_test.go's "unresolved references fail"/"cyclic references fail"
// subtests already cover one fixed 2-key example of each; this generalizes
// across randomly generated graph shapes and depths.
//
// This is its own scope/file (config-property), not folded into
// TestScopeConfigStrict, mirroring why config/config-local/config-strict
// already live in three separate scope files: a rapid.Check budget and its
// shrinking/failure-corpus behavior are a different testing mode than the
// deterministic table already in strict_test.go.
//
// rapid persists a minimized failing case under testdata/rapid/<test
// name>/ the first time a property fails. That directory does not exist
// yet (every property here is written to pass deterministically); if one
// ever does fail, commit the generated regression file rather than
// treating it as scratch output -- it becomes a permanent replay fixture
// for this property.
package projectconfig_test

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
	"pgregory.net/rapid"

	"github.com/lnorton89/golc/internal/command"
	"github.com/lnorton89/golc/internal/projectconfig"
)

var _ = command.MustDeclareScope(command.ScopeRegistration{
	Scope:   "config-property",
	Summary: "Property-based (pgregory.net/rapid) tests for typed cross-concern reference resolution.",
})

// referencePropertySpec declares one synthetic concern owning exactly the
// given keys, each accepting any literal (an open KeySpec{}), so the
// property isolates reference-graph resolution from unrelated value-shape
// validation (already covered by strict_test.go's many examples).
func referencePropertySpec(keys []string) projectconfig.Spec {
	fields := make(map[string]projectconfig.KeySpec, len(keys))
	for _, key := range keys {
		fields[key] = projectconfig.KeySpec{}
	}
	return projectconfig.Spec{Concerns: []projectconfig.ConcernSpec{
		{ID: "generated", Path: "config/generated.toml", Keys: fields},
	}}
}

// writeReferencePropertyRepository materializes the minimal root index plus
// one concern file declaring exactly the given key -> raw value pairs (a
// literal or a "ref:<key>" pointer), mirroring strict_test.go's
// writeStrictRepository fixture shape.
func writeReferencePropertyRepository(t *testing.T, keys []string, raw map[string]string) string {
	t.Helper()
	root := t.TempDir()
	require.NoError(t, os.WriteFile(filepath.Join(root, "golc.project.toml"),
		[]byte("schema_version = 2\n\n[[concerns]]\nid = \"generated\"\npath = \"config/generated.toml\"\n"), 0o644),
		"write root index")

	var concern strings.Builder
	concern.WriteString("schema_version = 2\n\n")
	for _, key := range keys {
		fmt.Fprintf(&concern, "%s = %q\n", key, raw[key])
	}
	require.NoError(t, os.MkdirAll(filepath.Join(root, "config"), 0o755), "mkdir config")
	require.NoError(t, os.WriteFile(filepath.Join(root, "config", "generated.toml"), []byte(concern.String()), 0o644),
		"write generated concern")
	return root
}

// literalGen draws a short lowercase-alnum literal; its alphabet excludes
// ':' so it can never collide with the "ref:" prefix.
var literalGen = rapid.StringMatching(`[a-z][a-z0-9]{0,7}`)

// genKeys returns n canonical, collision-free key names for the generated
// concern.
func genKeys(n int) []string {
	keys := make([]string, n)
	for i := range keys {
		keys[i] = fmt.Sprintf("genk%d", i)
	}
	return keys
}

// TestScopeConfigProperty is the exact quick-test marker for scope
// "config-property" (test --quick --scope config-property).
func TestScopeConfigProperty(t *testing.T) {
	t.Run("acyclic reference chains of any depth resolve to their terminal literal", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			n := rapid.IntRange(1, 8).Draw(rt, "n")
			keys := genKeys(n)

			raw := make(map[string]string, n)
			literal := make(map[string]string, n)
			isRef := make(map[string]bool, n)
			refTarget := make(map[string]int, n)

			// key 0 is always a literal; each later key is either its own
			// literal or a "ref:" to a strictly earlier key -- this makes
			// the whole graph acyclic and fully resolvable by construction,
			// regardless of shape (deep chains, fan-in "diamonds" sharing
			// one target, disconnected literals, etc.).
			literal[keys[0]] = literalGen.Draw(rt, "literal0")
			raw[keys[0]] = literal[keys[0]]
			for i := 1; i < n; i++ {
				if rapid.Bool().Draw(rt, fmt.Sprintf("isRef%d", i)) {
					target := rapid.IntRange(0, i-1).Draw(rt, fmt.Sprintf("target%d", i))
					isRef[keys[i]], refTarget[keys[i]] = true, target
					raw[keys[i]] = "ref:" + keys[target]
				} else {
					literal[keys[i]] = literalGen.Draw(rt, fmt.Sprintf("literal%d", i))
					raw[keys[i]] = literal[keys[i]]
				}
			}

			expected := make([]string, n)
			for i := 0; i < n; i++ {
				cursor := i
				for isRef[keys[cursor]] {
					cursor = refTarget[keys[cursor]]
				}
				expected[i] = literal[keys[cursor]]
			}

			root := writeReferencePropertyRepository(t, keys, raw)
			resolved, warnings, err := projectconfig.ValidateRepository(root, referencePropertySpec(keys))
			require.NoError(t, err, "acyclic reference graph must resolve: raw=%v", raw)
			require.Empty(t, warnings)
			for i, key := range keys {
				require.Equal(t, expected[i], resolved[key], "key %s resolved to the wrong terminal literal", key)
			}
		})
	})

	t.Run("a reference cycle of any length fails with GOLC_CONFIG_REF_CYCLE", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			n := rapid.IntRange(1, 6).Draw(rt, "n") // n=1 is a self-reference cycle
			keys := genKeys(n)
			raw := make(map[string]string, n)
			for i := 0; i < n; i++ {
				raw[keys[i]] = "ref:" + keys[(i+1)%n]
			}
			root := writeReferencePropertyRepository(t, keys, raw)
			_, _, err := projectconfig.ValidateRepository(root, referencePropertySpec(keys))
			require.ErrorContains(t, err, "GOLC_CONFIG_REF_CYCLE", "raw=%v", raw)
		})
	})

	t.Run("a reference to an undeclared key fails with GOLC_CONFIG_REF_UNRESOLVED", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			n := rapid.IntRange(1, 6).Draw(rt, "n")
			keys := genKeys(n)
			dangling := rapid.IntRange(0, n-1).Draw(rt, "dangling")
			raw := make(map[string]string, n)
			for i := 0; i < n; i++ {
				if i == dangling {
					raw[keys[i]] = "ref:missing.target" // never a declared key
				} else {
					raw[keys[i]] = literalGen.Draw(rt, fmt.Sprintf("literal%d", i))
				}
			}
			root := writeReferencePropertyRepository(t, keys, raw)
			_, _, err := projectconfig.ValidateRepository(root, referencePropertySpec(keys))
			require.ErrorContains(t, err, "GOLC_CONFIG_REF_UNRESOLVED", "raw=%v", raw)
		})
	})
}
