import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

import { describe, expect, it } from "vitest";

import * as designSystem from "./index";

type InventoryRecord = { name: string; kind: "primitive" | "pattern"; exportPath: string; guideAnchor: string; testPath: string };

describe("public design-system inventory", () => {
  it("has one inventory identity for every public export and guide marker", async () => {
    const root = resolve(process.cwd());
    const inventory = JSON.parse(await readFile(resolve(root, "design-system/components.json"), "utf8")) as { components: InventoryRecord[] };
    const guide = await readFile(resolve(root, "DESIGN_SYSTEM.md"), "utf8");

    expect(inventory.components.length).toBeGreaterThan(20);
    expect(guide).toContain("<!-- DESIGN-SYSTEM-INVENTORY:START generated by npm run generate:design-system -->");
    expect(guide).toContain("<!-- DESIGN-SYSTEM-INVENTORY:END -->");
    expect(new Set(inventory.components.map((component) => component.name)).size).toBe(inventory.components.length);
    for (const component of inventory.components) {
      expect(designSystem).toHaveProperty(component.name);
      expect(guide).toContain(component.guideAnchor);
    }
    expect(Object.keys(designSystem).sort()).toEqual(inventory.components.map((component) => component.name).sort());
  });
});
