// GENERATED by frontend/scripts/design-system/generate.mjs. DO NOT EDIT.
export const semanticTokenNames = [
  "action.destructive",
  "action.on-destructive",
  "action.on-primary",
  "action.primary",
  "action.primary-active",
  "action.primary-hover",
  "border.default",
  "border.destructive",
  "border.selected",
  "border.strong",
  "status.armed",
  "status.blackout",
  "status.frame-lock",
  "status.live",
  "status.offline",
  "status.on-armed",
  "status.on-blackout",
  "status.on-frame-lock",
  "status.on-live",
  "status.on-offline",
  "status.on-revoked",
  "status.revoked",
  "surface.canvas",
  "surface.control",
  "surface.overlay",
  "surface.panel",
  "surface.panel-subdued",
  "surface.scrim",
  "surface.selected",
  "text.inverse",
  "text.link",
  "text.muted",
  "text.primary",
  "text.secondary"
] as const;
export type SemanticTokenName = (typeof semanticTokenNames)[number];
export const themeNames = [
  "acid",
  "catppuccin",
  "default",
  "dracula",
  "everforest",
  "gruvbox",
  "nord",
  "one-dark",
  "rainbow",
  "rose-pine",
  "solarized",
  "tokyo"
] as const;
export type DesignSystemThemeName = (typeof themeNames)[number];
export const themeModes = [
  "dark",
  "light"
] as const;
export type DesignSystemThemeMode = (typeof themeModes)[number];
export const semanticTokenCSSVariables: Readonly<Record<SemanticTokenName, `--ds-${string}`>> = Object.freeze({
  "action.destructive": "--ds-action-destructive",
  "action.on-destructive": "--ds-action-on-destructive",
  "action.on-primary": "--ds-action-on-primary",
  "action.primary": "--ds-action-primary",
  "action.primary-active": "--ds-action-primary-active",
  "action.primary-hover": "--ds-action-primary-hover",
  "border.default": "--ds-border-default",
  "border.destructive": "--ds-border-destructive",
  "border.selected": "--ds-border-selected",
  "border.strong": "--ds-border-strong",
  "status.armed": "--ds-status-armed",
  "status.blackout": "--ds-status-blackout",
  "status.frame-lock": "--ds-status-frame-lock",
  "status.live": "--ds-status-live",
  "status.offline": "--ds-status-offline",
  "status.on-armed": "--ds-status-on-armed",
  "status.on-blackout": "--ds-status-on-blackout",
  "status.on-frame-lock": "--ds-status-on-frame-lock",
  "status.on-live": "--ds-status-on-live",
  "status.on-offline": "--ds-status-on-offline",
  "status.on-revoked": "--ds-status-on-revoked",
  "status.revoked": "--ds-status-revoked",
  "surface.canvas": "--ds-surface-canvas",
  "surface.control": "--ds-surface-control",
  "surface.overlay": "--ds-surface-overlay",
  "surface.panel": "--ds-surface-panel",
  "surface.panel-subdued": "--ds-surface-panel-subdued",
  "surface.scrim": "--ds-surface-scrim",
  "surface.selected": "--ds-surface-selected",
  "text.inverse": "--ds-text-inverse",
  "text.link": "--ds-text-link",
  "text.muted": "--ds-text-muted",
  "text.primary": "--ds-text-primary",
  "text.secondary": "--ds-text-secondary",
});
export const motionTokenNames = [
  "settle",
  "snap",
  "tap"
] as const;
export type MotionTokenName = (typeof motionTokenNames)[number];
export const motionTokens: Readonly<Record<MotionTokenName, { readonly ms: number; readonly easing: string }>> = Object.freeze({
  "settle": Object.freeze({ ms: 200, easing: "ease" }),
  "snap": Object.freeze({ ms: 0, easing: "linear" }),
  "tap": Object.freeze({ ms: 120, easing: "ease-out" }),
});
