// fixture_test.go proves FIXT-01's generated fixture schema contract
// (02-01-PLAN.md, Task 3): the "fixture" descriptor is registered exactly
// once, and its freshly generated bytes match the committed
// schemas/fixture.schema.json exactly -- no drift against the real
// checkout (mirrors generate_test.go's own registration/drift assertions,
// scoped to this one descriptor).
package contracts_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/lnorton89/golc/internal/contracts"
)

// repositoryRoot resolves the real checkout root from the package
// directory (pattern set by internal/bootstrap/bootstrap_test.go and
// internal/projectconfig/strict_test.go), so schemas/fixture.schema.json
// is checked exactly as committed, not from a synthetic fixture.
func repositoryRoot(t *testing.T) string {
	t.Helper()
	root, err := filepath.Abs(filepath.Join("..", ".."))
	require.NoError(t, err, "resolve repository root")
	_, err = os.Stat(filepath.Join(root, "golc.project.toml"))
	require.NoError(t, err, "repository root %q has no golc.project.toml", root)
	return root
}

func TestFixtureSchemaRegisteredAndDriftFree(t *testing.T) {
	count := 0
	for _, descriptor := range contracts.RegisteredSchemas() {
		if descriptor.Name == "fixture" {
			count++
			require.Equal(t, "schemas/fixture.schema.json", descriptor.OutputPath, "expected fixture schema output path schemas/fixture.schema.json")
		}
	}
	require.Equal(t, 1, count, "expected the \"fixture\" schema descriptor registered exactly once")

	root := repositoryRoot(t)
	changed, err := contracts.CheckDrift(root)
	require.NoError(t, err, "CheckDrift failed")
	for _, path := range changed {
		require.NotEqual(t, "schemas/fixture.schema.json", path, "schemas/fixture.schema.json has drift against internal/fixture.FixtureDefinition; run `generate` to refresh it")
	}

	data, err := os.ReadFile(filepath.Join(root, "schemas", "fixture.schema.json"))
	require.NoError(t, err, "expected schemas/fixture.schema.json to exist")
	// Mirrors generate.go's fixed generatedMarker comment (renderSchema
	// always sets it when the factory does not).
	require.Contains(t, string(data), "GENERATED by github.com/lnorton89/golc/internal/contracts. DO NOT EDIT.", "expected schemas/fixture.schema.json to carry the internal/contracts generated marker")
}
