// fixture_test.go proves FIXT-01's generated fixture schema contract
// (02-01-PLAN.md, Task 3): the "fixture" descriptor is registered exactly
// once, and its freshly generated bytes match the committed
// schemas/fixture.schema.json exactly -- no drift against the real
// checkout (mirrors generate_test.go's own registration/drift assertions,
// scoped to this one descriptor).
package contracts_test

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"

	"github.com/lnorton89/golc/internal/contracts"
)

// repositoryRoot resolves the real checkout root from the package
// directory (pattern set by internal/bootstrap/bootstrap_test.go and
// internal/projectconfig/strict_test.go), so schemas/fixture.schema.json
// is checked exactly as committed, not from a synthetic fixture.
func repositoryRoot(t *testing.T) string {
	t.Helper()
	root, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatalf("resolve repository root: %v", err)
	}
	if _, err := os.Stat(filepath.Join(root, "golc.project.toml")); err != nil {
		t.Fatalf("repository root %q has no golc.project.toml: %v", root, err)
	}
	return root
}

func TestFixtureSchemaRegisteredAndDriftFree(t *testing.T) {
	count := 0
	for _, descriptor := range contracts.RegisteredSchemas() {
		if descriptor.Name == "fixture" {
			count++
			if descriptor.OutputPath != "schemas/fixture.schema.json" {
				t.Fatalf("expected fixture schema output path schemas/fixture.schema.json, got %q", descriptor.OutputPath)
			}
		}
	}
	if count != 1 {
		t.Fatalf("expected the \"fixture\" schema descriptor registered exactly once, got %d", count)
	}

	root := repositoryRoot(t)
	changed, err := contracts.CheckDrift(root)
	if err != nil {
		t.Fatalf("CheckDrift failed: %v", err)
	}
	for _, path := range changed {
		if path == "schemas/fixture.schema.json" {
			t.Fatalf("schemas/fixture.schema.json has drift against internal/fixture.FixtureDefinition; run `generate` to refresh it")
		}
	}

	data, err := os.ReadFile(filepath.Join(root, "schemas", "fixture.schema.json"))
	if err != nil {
		t.Fatalf("expected schemas/fixture.schema.json to exist: %v", err)
	}
	// Mirrors generate.go's fixed generatedMarker comment (renderSchema
	// always sets it when the factory does not).
	if !bytes.Contains(data, []byte("GENERATED by github.com/lnorton89/golc/internal/contracts. DO NOT EDIT.")) {
		t.Fatalf("expected schemas/fixture.schema.json to carry the internal/contracts generated marker, got %s", data)
	}
}
