// generate.go implements the deterministic strict Draft 2020-12 contract
// generator CONTEXT D-08 requires: a compile-safe schema registry, byte-
// stable generation from the authoritative Go type projections in
// model.go, and read-only drift checking that never rewrites committed
// bytes.
//
// Contract files self-register their descriptors from a package-level var
// initializer through MustRegisterSchema, mirroring the
// MustDeclareRoute/MustDeclareScope self-registration idiom
// internal/command/router.go already establishes (CONTEXT D-03): a later
// contract file (for example a future Linear mapping or plan schema)
// becomes part of GenerateAll/GenerateInto/CheckDrift without editing this
// file or any central switch (T-01-10R: no duplicate or order-dependent
// registration can omit or silently overwrite a committed contract).
package contracts

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/invopop/jsonschema"
)

// generatedMarker is the fixed source-of-truth comment every generated
// schema carries (D-08: generated bytes always name their source package
// so a reviewer never mistakes them for hand-authored input).
const generatedMarker = "GENERATED by github.com/lnorton89/golc/internal/contracts. DO NOT EDIT."

// SchemaDescriptor is one committed Draft 2020-12 schema this package
// knows how to generate: a stable registry name, the repository-relative
// path its committed bytes live at, and a factory that reflects the
// authoritative Go type into a schema value.
type SchemaDescriptor struct {
	// Name is the stable registry identifier, for example
	// "config-toolchain". It is never a file path and never changes when
	// the output path does.
	Name string
	// OutputPath is the repository-relative committed schema path, for
	// example "schemas/config-toolchain.schema.json".
	OutputPath string
	// Schema builds a fresh reflection of the projected Go type on every
	// call. GenerateAll, GenerateInto, and CheckDrift all invoke it
	// directly rather than caching a shared *jsonschema.Schema value, so
	// no caller can observe a mutation made by another caller.
	Schema func() *jsonschema.Schema
}

// registry is the package-level compile-safe schema registry. byName
// preserves registration order (used only to build a fresh, independent
// snapshot on every RegisteredSchemas call); names and paths exist purely
// for O(1) duplicate detection in RegisterSchema.
var registry = struct {
	byName []SchemaDescriptor
	names  map[string]struct{}
	paths  map[string]string
}{
	names: map[string]struct{}{},
	paths: map[string]string{},
}

// RegisterSchema adds one descriptor to the package-level registry. It
// rejects a blank or whitespace-only name, a blank output path, a nil
// schema factory, a name already registered, and an output path already
// claimed by a different descriptor.
func RegisterSchema(descriptor SchemaDescriptor) error {
	name := strings.TrimSpace(descriptor.Name)
	if name == "" {
		return fmt.Errorf("GOLC_CONTRACTS_NAME_EMPTY: schema descriptor name is blank")
	}
	outputPath := strings.TrimSpace(descriptor.OutputPath)
	if outputPath == "" {
		return fmt.Errorf("GOLC_CONTRACTS_OUTPUT_EMPTY: schema %q has a blank output path", name)
	}
	if descriptor.Schema == nil {
		return fmt.Errorf("GOLC_CONTRACTS_FACTORY_NIL: schema %q has no schema factory", name)
	}
	if _, exists := registry.names[name]; exists {
		return fmt.Errorf("GOLC_CONTRACTS_NAME_DUPLICATE: schema %q is already registered", name)
	}
	if owner, exists := registry.paths[outputPath]; exists {
		return fmt.Errorf(
			"GOLC_CONTRACTS_OUTPUT_DUPLICATE: output path %q is already registered by schema %q", outputPath, owner)
	}

	descriptor.Name = name
	descriptor.OutputPath = outputPath
	registry.names[name] = struct{}{}
	registry.paths[outputPath] = name
	registry.byName = append(registry.byName, descriptor)
	return nil
}

// MustRegisterSchema is the compile-safe self-registration entrypoint a
// contract file calls from a package-level var initializer:
//
//	var _ = contracts.MustRegisterSchema(contracts.SchemaDescriptor{...})
//
// A rejected registration (RegisterSchema's own validation) panics
// immediately at program startup rather than surfacing as a later, harder
// to diagnose generation failure.
func MustRegisterSchema(descriptor SchemaDescriptor) SchemaDescriptor {
	if err := RegisterSchema(descriptor); err != nil {
		panic(err.Error())
	}
	return descriptor
}

// RegisteredSchemas returns every registered descriptor as a defensive
// snapshot sorted by stable name: mutating the returned slice, or any
// descriptor value inside it, never affects the package-level registry,
// and repeated calls made without an intervening registration are
// byte-identical in order.
func RegisteredSchemas() []SchemaDescriptor {
	byName := make(map[string]SchemaDescriptor, len(registry.byName))
	names := make([]string, 0, len(registry.byName))
	for _, descriptor := range registry.byName {
		byName[descriptor.Name] = descriptor
		names = append(names, descriptor.Name)
	}
	sort.Strings(names)

	snapshot := make([]SchemaDescriptor, 0, len(names))
	for _, name := range names {
		snapshot = append(snapshot, byName[name])
	}
	return snapshot
}

// renderSchema builds one descriptor's normalized, committed-ready bytes:
// the reflected schema receives the fixed generated marker (unless the
// factory already set one) and a defensive additionalProperties:false at
// its root, then NormalizeSchema sorts and LF-normalizes the result so
// output is byte-identical on Windows and CI (D-08).
func renderSchema(descriptor SchemaDescriptor) ([]byte, error) {
	schema := descriptor.Schema()
	if schema == nil {
		return nil, fmt.Errorf("GOLC_CONTRACTS_SCHEMA_NIL: schema %q produced a nil value", descriptor.Name)
	}
	if schema.Comments == "" {
		schema.Comments = generatedMarker + " Schema: " + descriptor.Name + "."
	}
	if schema.AdditionalProperties == nil {
		schema.AdditionalProperties = jsonschema.FalseSchema
	}
	return NormalizeSchema(schema)
}

// GenerateInto writes every registered descriptor's normalized schema
// under targetRoot instead of the committed repository root, so a caller
// (including CheckDrift) can generate into a disposable directory without
// ever touching committed bytes. Every registered descriptor's factory is
// invoked exactly once per call, in the same stable name-sorted order
// RegisteredSchemas returns.
func GenerateInto(targetRoot string) error {
	for _, descriptor := range RegisteredSchemas() {
		payload, err := renderSchema(descriptor)
		if err != nil {
			return err
		}
		destination := filepath.Join(targetRoot, filepath.FromSlash(descriptor.OutputPath))
		if err := os.MkdirAll(filepath.Dir(destination), 0o755); err != nil {
			return fmt.Errorf("GOLC_CONTRACTS_WRITE: %s: %v", descriptor.OutputPath, err)
		}
		if err := os.WriteFile(destination, payload, 0o644); err != nil {
			return fmt.Errorf("GOLC_CONTRACTS_WRITE: %s: %v", descriptor.OutputPath, err)
		}
	}
	return nil
}

// GenerateAll regenerates every registered descriptor's schema directly at
// its committed repository-relative path under root, the entrypoint a
// future `generate` command wires up. It shares GenerateInto's exactly-
// once traversal and stable ordering; the two names exist because writing
// the real committed location and writing a disposable comparison target
// are different callers' intents even though the underlying write is the
// same operation.
func GenerateAll(root string) error {
	return GenerateInto(root)
}

// CheckDrift compares every registered descriptor's freshly generated
// bytes against its committed bytes without ever writing to the committed
// location: generation happens once into a disposable temporary
// directory, and only that directory's output is read back for
// comparison. It returns the OutputPaths that differ (including a
// registered schema with no committed file yet) in stable sorted order.
func CheckDrift(root string) ([]string, error) {
	tempDir, err := os.MkdirTemp("", "golc-contracts-check-*")
	if err != nil {
		return nil, fmt.Errorf("GOLC_CONTRACTS_TEMP: %v", err)
	}
	defer os.RemoveAll(tempDir)

	if err := GenerateInto(tempDir); err != nil {
		return nil, err
	}

	changed := []string{}
	for _, descriptor := range RegisteredSchemas() {
		generatedPath := filepath.Join(tempDir, filepath.FromSlash(descriptor.OutputPath))
		generatedBytes, err := os.ReadFile(generatedPath)
		if err != nil {
			return nil, fmt.Errorf("GOLC_CONTRACTS_READ: %s: %v", descriptor.OutputPath, err)
		}

		committedPath := filepath.Join(root, filepath.FromSlash(descriptor.OutputPath))
		committedBytes, err := os.ReadFile(committedPath)
		if err != nil {
			if os.IsNotExist(err) {
				changed = append(changed, descriptor.OutputPath)
				continue
			}
			return nil, fmt.Errorf("GOLC_CONTRACTS_READ: %s: %v", descriptor.OutputPath, err)
		}

		if !bytes.Equal(committedBytes, generatedBytes) {
			changed = append(changed, descriptor.OutputPath)
		}
	}
	sort.Strings(changed)
	return changed, nil
}
