// check.go is the check command file: it owns the "check" scope and
// self-registers the exact check route through the package declaration
// entrypoints (CONTEXT D-03/D-10) — the central router is never edited.
// The handler composes every strict project validation this repository
// already owns rather than re-implementing any of it:
//   - internal/projectconfig.ValidateRepository (Plan 03/18): root index
//     discovery, every concern decoded in isolation, single-authority
//     ownership, and the cross-concern "ref:" reference graph.
//   - internal/projectconfig.ResolveContainedPath (Plan 18): on-disk
//     repository containment for every canonical key whose resolved value
//     is a declared repository-relative path.
//   - internal/contracts.CheckDrift (Plan 04): read-only comparison of
//     every committed schema against its freshly generated bytes.
//
// Route registration follows the same dash-word precedent generate.go
// documents: one exact route, "check", is declared here; its handler
// strictly accepts exactly "--concern <name>" and rejects anything else.
// The user-facing command "check --concern project" is both exact and
// reachable through this single registration.
package command

import (
	"fmt"
	"sort"
	"strings"

	"github.com/lnorton89/golc/internal/contracts"
	"github.com/lnorton89/golc/internal/projectconfig"
)

var _ = MustDeclareScope(ScopeRegistration{
	Scope:   "check",
	Summary: "Offline strict validation of one repository concern.",
})

var _ = MustDeclareRoute(CommandRegistration{
	Route: "check",
	Summary: "Run a strict offline concern check: check --concern <name>. Concern \"project\" validates " +
		"the root index, every concern, the authority/reference graph, path containment, and generated-schema drift.",
	Handler: runCheck,
})

// runCheck serves the self-registered "check" route.
func runCheck(request Request) Result {
	concern, err := parseCheckArgs(request.Args)
	if err != nil {
		return Result{ExitCode: 2, Stderr: []byte(err.Error() + "\n")}
	}
	switch concern {
	case "project":
		return runProjectCheck(request.Root)
	default:
		return Result{ExitCode: 2, Stderr: []byte(fmt.Sprintf("GOLC_CHECK_CONCERN_UNKNOWN: %q\n", concern))}
	}
}

// parseCheckArgs accepts exactly "--concern <name>".
func parseCheckArgs(args []string) (string, error) {
	concern := ""
	for i := 0; i < len(args); {
		argument := args[i]
		switch {
		case argument == "--concern":
			if concern != "" {
				return "", fmt.Errorf("GOLC_CHECK_USAGE: --concern may be given only once")
			}
			if i+1 >= len(args) {
				return "", fmt.Errorf("GOLC_CHECK_USAGE: --concern requires a value")
			}
			concern = args[i+1]
			i += 2
		default:
			return "", fmt.Errorf("GOLC_CHECK_USAGE: unsupported argument %q; usage: check --concern <name>", argument)
		}
	}
	if concern == "" {
		return "", fmt.Errorf("GOLC_CHECK_USAGE: usage: check --concern <name>")
	}
	return concern, nil
}

// projectCheckPathKeys names every canonical key whose resolved value is a
// repository-relative path (CONTEXT D-05/D-09). ValidateRepository already
// enforces each value's KeySpec pattern; this list additionally routes
// every one of those literals through ResolveContainedPath's on-disk
// symlink/reparse containment check before the project check can pass.
var projectCheckPathKeys = []string{
	"cache.downloads",
	"cache.gomodcache",
	"cache.gocache",
	"commands.cli_binary",
	"generation.schemas_dir",
	"linear.mapping_file",
}

// runProjectCheck composes every strict project-concern validation this
// repository owns and never writes anything: it is read-only end to end.
func runProjectCheck(root string) Result {
	var report strings.Builder

	spec := projectconfig.DefaultSpec()
	resolved, warnings, err := projectconfig.ValidateRepository(root, spec)
	if err != nil {
		return Result{ExitCode: 1, Stderr: []byte("GOLC_CHECK_PROJECT_CONFIG: " + err.Error() + "\n")}
	}
	fmt.Fprintf(&report,
		"check --concern project: root index, %d concerns, and the authority/reference graph are strict-clean.\n",
		len(spec.Concerns))

	sortedWarnings := append([]projectconfig.Diagnostic(nil), warnings...)
	sort.Slice(sortedWarnings, func(i, j int) bool {
		return sortedWarnings[i].String() < sortedWarnings[j].String()
	})
	for _, warning := range sortedWarnings {
		fmt.Fprintf(&report, "%s\n", warning.String())
	}

	for _, key := range projectCheckPathKeys {
		value, declared := resolved[key]
		if !declared {
			return Result{ExitCode: 1, Stderr: []byte(fmt.Sprintf(
				"GOLC_CHECK_PROJECT_PATH: %q is not declared by the resolved configuration\n", key))}
		}
		if _, err := projectconfig.ResolveContainedPath(root, value); err != nil {
			return Result{ExitCode: 1, Stderr: []byte(fmt.Sprintf("GOLC_CHECK_PROJECT_PATH: %s: %v\n", key, err))}
		}
	}
	report.WriteString("check --concern project: every declared path stays repository-contained.\n")

	changed, err := contracts.CheckDrift(root)
	if err != nil {
		return Result{ExitCode: 1, Stderr: []byte("GOLC_CHECK_PROJECT_GENERATED: " + err.Error() + "\n")}
	}
	if len(changed) > 0 {
		return Result{ExitCode: 1, Stderr: []byte(fmt.Sprintf(
			"GOLC_CHECK_PROJECT_GENERATED: committed schemas drifted: %s\n", strings.Join(changed, ", ")))}
	}
	report.WriteString("check --concern project: every committed schema matches its generated source.\n")

	return Result{Stdout: []byte(report.String())}
}
