// check.go is the check command file: it owns the "check" scope and
// self-registers the exact check route through the package declaration
// entrypoints (CONTEXT D-03/D-10) — the central router is never edited.
// The handler composes every strict project validation this repository
// already owns rather than re-implementing any of it:
//   - internal/projectconfig.ValidateRepository (Plan 03/18): root index
//     discovery, every concern decoded in isolation, single-authority
//     ownership, and the cross-concern "ref:" reference graph.
//   - internal/projectconfig.ResolveContainedPath (Plan 18): on-disk
//     repository containment for every canonical key whose resolved value
//     is a declared repository-relative path.
//   - internal/contracts.CheckDrift (Plan 04): read-only comparison of
//     every committed schema against its freshly generated bytes.
//   - internal/delivery.LoadGraph/RunOffline (Plan 06): the one
//     declarative offline core graph (generate, check --concern project,
//     build, test --quick), executed with the network-denied environment
//     and deny transport installed.
//
// Route registration follows the same dash-word precedent generate.go
// documents: one exact route, "check", is declared here; its handler
// strictly accepts exactly "--concern <name>" or "--offline" (mutually
// exclusive) and rejects anything else. The user-facing commands
// "check --concern project" and "check --offline" are both exact and
// reachable through this single registration.
package command

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/lnorton89/golc/internal/contracts"
	"github.com/lnorton89/golc/internal/delivery"
	"github.com/lnorton89/golc/internal/projectconfig"
	"github.com/lnorton89/golc/internal/security"
)

var _ = MustDeclareScope(ScopeRegistration{
	Scope:   "check",
	Summary: "Offline strict validation of one repository concern.",
})

var _ = MustDeclareRoute(CommandRegistration{
	Route: "check",
	Summary: "Run a strict offline concern check: check --concern <name>|--offline|--command-parity. Concern " +
		"\"project\" validates the root index, every concern, the authority/reference graph, path containment, " +
		"generated-schema drift, and the cross-artifact fake-secret canary; --offline runs the complete " +
		"generate/check/build/test core graph with network denied; --command-parity proves the committed Windows " +
		"PR workflow invokes exactly config/commands.toml's commands.pr.steps graph in order, with no Linear " +
		"secret reference, remote trigger, or apply-capable command reachable (CONTEXT D-03/D-10/D-16).",
	Handler: runCheck,
})

// checkArgs is the parsed shape of one check invocation: exactly one of
// concern (check --concern <name>), offline (check --offline), or
// commandParity (check --command-parity) is set.
type checkArgs struct {
	concern       string
	offline       bool
	commandParity bool
}

// runCheck serves the self-registered "check" route.
func runCheck(request Request) Result {
	parsed, err := parseCheckArgs(request.Args)
	if err != nil {
		return Result{ExitCode: 2, Stderr: []byte(err.Error() + "\n")}
	}
	if parsed.offline {
		return runCheckOffline(request.Root)
	}
	if parsed.commandParity {
		return runCheckCommandParity(request.Root)
	}
	switch parsed.concern {
	case "project":
		return runProjectCheck(request.Root)
	default:
		return Result{ExitCode: 2, Stderr: []byte(fmt.Sprintf("GOLC_CHECK_CONCERN_UNKNOWN: %q\n", parsed.concern))}
	}
}

// parseCheckArgs accepts exactly "--concern <name>", "--offline", or
// "--command-parity"; the three forms are mutually exclusive.
func parseCheckArgs(args []string) (checkArgs, error) {
	parsed := checkArgs{}
	exclusiveSet := func() bool {
		return parsed.concern != "" || parsed.offline || parsed.commandParity
	}
	for i := 0; i < len(args); {
		argument := args[i]
		switch {
		case argument == "--concern":
			if exclusiveSet() {
				return checkArgs{}, fmt.Errorf(
					"GOLC_CHECK_USAGE: --concern, --offline, and --command-parity are mutually exclusive")
			}
			if i+1 >= len(args) {
				return checkArgs{}, fmt.Errorf("GOLC_CHECK_USAGE: --concern requires a value")
			}
			parsed.concern = args[i+1]
			i += 2
		case argument == "--offline":
			if exclusiveSet() {
				return checkArgs{}, fmt.Errorf(
					"GOLC_CHECK_USAGE: --concern, --offline, and --command-parity are mutually exclusive")
			}
			parsed.offline = true
			i++
		case argument == "--command-parity":
			if exclusiveSet() {
				return checkArgs{}, fmt.Errorf(
					"GOLC_CHECK_USAGE: --concern, --offline, and --command-parity are mutually exclusive")
			}
			parsed.commandParity = true
			i++
		default:
			return checkArgs{}, fmt.Errorf(
				"GOLC_CHECK_USAGE: unsupported argument %q; usage: check --concern <name>|--offline|--command-parity", argument)
		}
	}
	if parsed.concern == "" && !parsed.offline && !parsed.commandParity {
		return checkArgs{}, fmt.Errorf("GOLC_CHECK_USAGE: usage: check --concern <name>|--offline|--command-parity")
	}
	return parsed, nil
}

// runCheckOffline serves "check --offline" (CONTEXT D-02/D-10, T-01-15,
// T-01-17): it loads the one declarative offline core graph
// (internal/delivery.LoadGraph), validates it is well-formed and
// duplicate-safe (ValidateParity), and executes every step
// (generate, check --concern project, build, test --quick) in order
// through the in-process command registry with the offline
// environment/deny transport installed (RunOffline). Any step failing —
// including one that unexpectedly attempts network access — fails this
// command with the failing step's own diagnostic.
func runCheckOffline(root string) Result {
	graph, err := delivery.LoadGraph(root)
	if err != nil {
		return Result{ExitCode: 1, Stderr: []byte("GOLC_CHECK_OFFLINE: " + err.Error() + "\n")}
	}
	if err := delivery.ValidateParity(graph); err != nil {
		return Result{ExitCode: 1, Stderr: []byte("GOLC_CHECK_OFFLINE: " + err.Error() + "\n")}
	}

	registry, err := NewDefaultCommandRegistry()
	if err != nil {
		return Result{ExitCode: 1, Stderr: []byte("GOLC_CHECK_OFFLINE: " + err.Error() + "\n")}
	}
	executor := func(route string, args []string) (int, []byte, []byte) {
		result := registry.Execute(Request{Root: root, Args: append([]string{route}, args...)})
		return result.ExitCode, result.Stdout, result.Stderr
	}

	var report bytes.Buffer
	results, runErr := delivery.RunOffline(graph, executor)
	for _, stepResult := range results {
		fmt.Fprintf(&report, "check --offline: step %q exited %d.\n", stepResult.Step.Name, stepResult.ExitCode)
		report.Write(stepResult.Stdout)
	}
	if runErr != nil {
		var failureDetail []byte
		if len(results) > 0 {
			failureDetail = results[len(results)-1].Stderr
		}
		stderr := append([]byte("GOLC_CHECK_OFFLINE: "+runErr.Error()+"\n"), failureDetail...)
		return Result{ExitCode: 1, Stdout: report.Bytes(), Stderr: stderr}
	}
	report.WriteString("check --offline: generate, check, build, and test all completed with network denied.\n")
	return Result{Stdout: report.Bytes()}
}

// projectCheckPathKeys names every canonical key whose resolved value is a
// repository-relative path (CONTEXT D-05/D-09). ValidateRepository already
// enforces each value's KeySpec pattern; this list additionally routes
// every one of those literals through ResolveContainedPath's on-disk
// symlink/reparse containment check before the project check can pass.
var projectCheckPathKeys = []string{
	"cache.downloads",
	"cache.gomodcache",
	"cache.gocache",
	"commands.cli_binary",
	"generation.schemas_dir",
	"linear.mapping_file",
}

// runProjectCheck composes every strict project-concern validation this
// repository owns and never writes anything: it is read-only end to end.
func runProjectCheck(root string) Result {
	var report strings.Builder

	spec := projectconfig.DefaultSpec()
	resolved, warnings, err := projectconfig.ValidateRepository(root, spec)
	if err != nil {
		return Result{ExitCode: 1, Stderr: []byte("GOLC_CHECK_PROJECT_CONFIG: " + err.Error() + "\n")}
	}
	fmt.Fprintf(&report,
		"check --concern project: root index, %d concerns, and the authority/reference graph are strict-clean.\n",
		len(spec.Concerns))

	sortedWarnings := append([]projectconfig.Diagnostic(nil), warnings...)
	sort.Slice(sortedWarnings, func(i, j int) bool {
		return sortedWarnings[i].String() < sortedWarnings[j].String()
	})
	for _, warning := range sortedWarnings {
		fmt.Fprintf(&report, "%s\n", warning.String())
	}

	for _, key := range projectCheckPathKeys {
		value, declared := resolved[key]
		if !declared {
			return Result{ExitCode: 1, Stderr: []byte(fmt.Sprintf(
				"GOLC_CHECK_PROJECT_PATH: %q is not declared by the resolved configuration\n", key))}
		}
		if _, err := projectconfig.ResolveContainedPath(root, value); err != nil {
			return Result{ExitCode: 1, Stderr: []byte(fmt.Sprintf("GOLC_CHECK_PROJECT_PATH: %s: %v\n", key, err))}
		}
	}
	report.WriteString("check --concern project: every declared path stays repository-contained.\n")

	changed, err := contracts.CheckDrift(root)
	if err != nil {
		return Result{ExitCode: 1, Stderr: []byte("GOLC_CHECK_PROJECT_GENERATED: " + err.Error() + "\n")}
	}
	if len(changed) > 0 {
		return Result{ExitCode: 1, Stderr: []byte(fmt.Sprintf(
			"GOLC_CHECK_PROJECT_GENERATED: committed schemas drifted: %s\n", strings.Join(changed, ", ")))}
	}
	report.WriteString("check --concern project: every committed schema matches its generated source.\n")

	sources, err := canaryScanSources(root, resolved)
	if err != nil {
		return Result{ExitCode: 1, Stderr: []byte("GOLC_CHECK_PROJECT_CANARY: " + err.Error() + "\n")}
	}
	if violations := security.ScanCanaryAll(sources); len(violations) > 0 {
		details := make([]string, 0, len(violations))
		for _, violation := range violations {
			details = append(details, fmt.Sprintf("%s (token %q)", violation.Source, violation.Token))
		}
		return Result{ExitCode: 1, Stderr: []byte(fmt.Sprintf(
			"GOLC_CHECK_PROJECT_CANARY: fake-secret bytes found: %s\n", strings.Join(details, "; ")))}
	}
	report.WriteString("check --concern project: no fake-secret bytes found across generated schemas and the Linear map.\n")

	return Result{Stdout: []byte(report.String())}
}

// canaryScanSources collects every generated schema (T-01-18: information
// disclosure) plus the committed Linear map into one named byte set
// security.ScanCanaryAll can scan in a single pass. It reads only committed
// repository-relative paths already declared by contracts.RegisteredSchemas
// and the resolved "linear.mapping_file" canonical key -- no second,
// independently maintained inventory of scanned artifacts exists elsewhere.
func canaryScanSources(root string, resolved map[string]string) (map[string][]byte, error) {
	sources := map[string][]byte{}
	for _, descriptor := range contracts.RegisteredSchemas() {
		data, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(descriptor.OutputPath)))
		if err != nil {
			return nil, fmt.Errorf("%s: %v", descriptor.OutputPath, err)
		}
		sources["schema:"+descriptor.OutputPath] = data
	}
	if mapPath, declared := resolved["linear.mapping_file"]; declared {
		full := filepath.Join(root, filepath.FromSlash(mapPath))
		data, err := os.ReadFile(full)
		if err != nil {
			return nil, fmt.Errorf("%s: %v", mapPath, err)
		}
		sources["map:"+mapPath] = data
	}
	return sources, nil
}

// prWorkflowPath is the exact committed Windows PR workflow
// runCheckCommandParity parses (CONTEXT D-03/D-10/D-16). No second,
// independently maintained workflow path exists in this repository.
const prWorkflowPath = ".github/workflows/check.yml"

// prRunDirectivePattern recognizes every YAML run key, including spacing
// variants that the strict invocation pattern below deliberately rejects.
// Executable workflow content is therefore closed-world.
var prRunDirectivePattern = regexp.MustCompile(`^\s*run\s*:`)

// prMageInvocationPattern is the only executable step shape permitted in
// the PR workflow. Mage accepts target spelling case-insensitively, but no
// target argument, shell operator, prefix, suffix, or multiline body is
// legal here.
var prMageInvocationPattern = regexp.MustCompile(`^run:\s+mage\s+([A-Za-z][A-Za-z0-9]*)$`)

// prForbiddenTokens names every substring that must never appear in the
// committed PR workflow (CONTEXT D-16): a Linear secret reference or an
// apply-capable (mutation) command.
var prForbiddenTokens = []string{
	"LINEAR_API_KEY",
	"LINEAR_TEAM_ID",
	"secrets.",
	"linear apply",
	"linear map migrate --write",
	"linear archive",
	"linear unlink",
}

// prForbiddenTriggers names every workflow trigger keyword that would let
// this workflow run from something other than an untrusted pull_request
// event (CONTEXT D-16): mutation must never become reachable through a
// second trigger path.
var prForbiddenTriggers = []string{"workflow_dispatch", "schedule:", "push:", "repository_dispatch"}

// workflowMageTargets returns every run directive's Mage target in file
// order and rejects any executable line outside the exact allowed shape.
func workflowMageTargets(data []byte) ([]string, error) {
	lines := strings.Split(strings.ReplaceAll(string(data), "\r\n", "\n"), "\n")
	targets := make([]string, 0)
	for lineIndex, line := range lines {
		if !prRunDirectivePattern.MatchString(line) {
			continue
		}
		trimmed := strings.TrimSpace(line)
		match := prMageInvocationPattern.FindStringSubmatch(trimmed)
		if match == nil {
			return nil, fmt.Errorf(
				"GOLC_CHECK_PARITY_RUN_INVALID: %s line %d must be exactly \"run: mage <Target>\", got %q",
				prWorkflowPath, lineIndex+1, trimmed)
		}
		targets = append(targets, match[1])
	}
	return targets, nil
}

// projectMageTarget resolves one workflow spelling through the shared
// descriptor registry and converts it generically to its graph invocation.
// Route descriptors contribute Route/Args; the bootstrap descriptor uses
// its registered target name as the graph route. PR is intentionally
// illegal because invoking it would recursively execute the entire graph.
func projectMageTarget(position int, spelling string) (delivery.Step, error) {
	target, found := delivery.LookupMageTarget(strings.ToLower(spelling))
	if !found {
		return delivery.Step{}, fmt.Errorf(
			"GOLC_CHECK_PARITY_TARGET_UNKNOWN: step %d: Mage target %q is not registered",
			position, spelling)
	}

	switch target.Kind {
	case delivery.MageTargetKindRoute:
		return delivery.Step{Route: target.Route, Args: append([]string(nil), target.Args...)}, nil
	case delivery.MageTargetKindBootstrap:
		return delivery.Step{Route: target.Name}, nil
	default:
		return delivery.Step{}, fmt.Errorf(
			"GOLC_CHECK_PARITY_TARGET_KIND: step %d: Mage target %q has invalid workflow kind %q",
			position, spelling, target.Kind)
	}
}

// validateCommandParity validates one workflow byte snapshot against one
// already-loaded configured PR graph. Expected behavior comes only from
// delivery.LoadPRGraph's result; actual behavior comes only from the shared
// Mage descriptor registry.
func validateCommandParity(graph delivery.Graph, data []byte) error {
	targetSpellings, err := workflowMageTargets(data)
	if err != nil {
		return err
	}

	actual := make([]delivery.Step, 0, len(targetSpellings))
	for index, spelling := range targetSpellings {
		step, err := projectMageTarget(index+1, spelling)
		if err != nil {
			return err
		}
		actual = append(actual, step)
	}

	if len(graph.Steps) != len(actual) {
		return fmt.Errorf(
			"GOLC_CHECK_PARITY_STEP_COUNT: config/commands.toml declares %d PR step(s) but %s invokes %d: expected %v, got %v",
			len(graph.Steps), prWorkflowPath, len(actual),
			formatParitySteps(graph.Steps), formatParitySteps(actual))
	}
	for index := range graph.Steps {
		expectedStep := graph.Steps[index]
		actualStep := actual[index]
		if expectedStep.Route != actualStep.Route || !equalParityArgs(expectedStep.Args, actualStep.Args) {
			return fmt.Errorf(
				"GOLC_CHECK_PARITY_STEP_MISMATCH: step %d: config/commands.toml declares %q but %s target %q resolves to %q",
				index+1, formatParityStep(expectedStep), prWorkflowPath,
				targetSpellings[index], formatParityStep(actualStep))
		}
	}

	text := string(data)
	for _, token := range prForbiddenTokens {
		if strings.Contains(text, token) {
			return fmt.Errorf(
				"GOLC_CHECK_PARITY_SECRET_OR_MUTATION: %s contains forbidden token %q",
				prWorkflowPath, token)
		}
	}
	for _, trigger := range prForbiddenTriggers {
		if strings.Contains(text, trigger) {
			return fmt.Errorf(
				"GOLC_CHECK_PARITY_TRIGGER_FORBIDDEN: %s declares forbidden trigger %q",
				prWorkflowPath, trigger)
		}
	}
	if !strings.Contains(text, "pull_request") {
		return fmt.Errorf(
			"GOLC_CHECK_PARITY_TRIGGER_MISSING: %s does not declare a pull_request trigger",
			prWorkflowPath)
	}
	return nil
}

func equalParityArgs(left, right []string) bool {
	if len(left) != len(right) {
		return false
	}
	for index := range left {
		if left[index] != right[index] {
			return false
		}
	}
	return true
}

func formatParityStep(step delivery.Step) string {
	return strings.TrimSpace(strings.Join(append([]string{step.Route}, step.Args...), " "))
}

func formatParitySteps(steps []delivery.Step) []string {
	formatted := make([]string, len(steps))
	for index, step := range steps {
		formatted[index] = formatParityStep(step)
	}
	return formatted
}

// runCheckCommandParity serves "check --command-parity" (CONTEXT D-03/
// D-10/D-16, T-01-19/T-01-20). It loads the configured PR graph exactly
// once, reads the workflow exactly once, and delegates descriptor-backed
// sequence comparison plus least-privilege scans to validateCommandParity.
func runCheckCommandParity(root string) Result {
	graph, err := delivery.LoadPRGraph(root)
	if err != nil {
		return Result{ExitCode: 1, Stderr: []byte("GOLC_CHECK_PARITY_CONFIG: " + err.Error() + "\n")}
	}

	workflowPath := filepath.Join(root, filepath.FromSlash(prWorkflowPath))
	data, err := os.ReadFile(workflowPath)
	if err != nil {
		return Result{ExitCode: 1, Stderr: []byte(fmt.Sprintf(
			"GOLC_CHECK_PARITY_WORKFLOW_MISSING: %s: %v\n", prWorkflowPath, err))}
	}

	if err := validateCommandParity(graph, data); err != nil {
		return Result{ExitCode: 1, Stderr: []byte(err.Error() + "\n")}
	}

	report := fmt.Sprintf(
		"check --command-parity: %d PR step(s) in %s exactly match config/commands.toml's commands.pr.steps in "+
			"order; no Linear secret reference, remote trigger, or apply-capable command was found.\n",
		len(graph.Steps), prWorkflowPath)
	return Result{Stdout: []byte(report)}
}
