// svc_script.go fills ScriptService, the Wails binding closing SCRP-01
// (08-04-PLAN.md Task 1): a user creates, inspects, edits, deletes, and
// assigns capability profiles to TypeScript automation scripts through the
// exact already-implemented, already-tested "script"* CLI routes
// (internal/command/script.go) via command.NewDefaultCommandRegistry --
// exactly the ProgrammingService/ShowService pattern (svc_programming.go/
// svc_show.go) this file mirrors -- so there is only one script mutation
// implementation in this codebase, never a second one duplicated for the
// GUI.
//
// SaveScriptSource cannot pass a multi-line TypeScript body as an argv
// value safely, and "script edit" takes --source-file: SaveScriptSource
// writes the source to a temp file (os.CreateTemp inside os.TempDir(),
// removed via defer) and passes that path to "script edit --source-file",
// guarded by the same maxScriptSourceBytes (1 MiB) bound 08-01's
// internal/command/script.go declares, checked before any write
// (T-08-03/T-08-12).
//
// ListScripts/GetScript decode "script list"/"script show"'s Stdout JSON
// with internal/strictjson.DecodeStrict into unexported wire types that
// mirror internal/command/script.go's own scriptListEntryView/scriptView
// shapes field-for-field/tag-for-tag, then flatten the nested
// capability_profile member into this package's own flat
// ScriptSummaryView/ScriptDetailView shape for the frontend.
package wails

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/lnorton89/golc/internal/command"
	"github.com/lnorton89/golc/internal/script"
	"github.com/lnorton89/golc/internal/strictjson"
)

// maxScriptSourceBytes bounds SaveScriptSource's input (T-08-03/T-08-12 DoS
// mitigation) -- mirrors internal/command/script.go's identical constant
// (unexported to that package, so this file keeps its own copy); a source
// larger than this is rejected with GOLC_SCRIPT_SOURCE_TOO_LARGE before any
// temp file is ever written.
const maxScriptSourceBytes = 1 << 20 // 1 MiB

// scriptSDKTypesRelPath is internal/scriptsdk/generate.go's own committed
// golc.d.ts output path (08-03-PLAN.md), kept here as a single literal
// rather than importing internal/scriptsdk directly: this package already
// builds its own command registry via internal/command exactly like every
// other route in this file, and 08-03 deliberately keeps SDK generation
// decoupled from serving the generated bytes to the frontend.
const scriptSDKTypesRelPath = "internal/scriptsdk/generated/golc.d.ts"

// ScriptService is bound to the frontend via cmd/golc-desktop/main.go's
// options.App{Bind: [...]}. root/showPath are the exact ShowState location
// every method acts against (mirrors ProgrammingService/ShowService's own
// fields). events is this service's own EventPusher (events.go's throttle
// scaffold) -- mirrors SafetyService/MidiService's identical
// self-constructed-in-NewXService pattern (own field, own Start/Stop
// lifecycle called by this service's own Start/StopScriptEventStream
// methods) rather than threading a shared *EventPusher through the
// constructor, so this service's lifecycle stays self-contained exactly
// like its siblings and cmd/golc-desktop/main.go needs no new wiring.
type ScriptService struct {
	pipeName string
	root     string
	showPath string
	events   *EventPusher

	mu           sync.Mutex
	streamCancel context.CancelFunc
	streamDone   chan struct{}
}

// NewScriptService constructs a ScriptService targeting pipeName (reserved,
// unused by this ShowState-only CRUD -- mirrors ProgrammingService/
// ShowService's own unused pipeName field) and the ShowState at showPath,
// resolved against root.
func NewScriptService(pipeName, root, showPath string) *ScriptService {
	return &ScriptService{pipeName: pipeName, root: root, showPath: showPath, events: NewEventPusher()}
}

// execute builds the default command registry and runs args against it,
// converting the internal/command.Result shape into this package's own
// Result shape (mirrors svc_programming.go/svc_show.go's identical
// helper).
func (s *ScriptService) execute(args ...string) Result {
	registry, err := command.NewDefaultCommandRegistry()
	if err != nil {
		return Result{ExitCode: 2, Stderr: fmt.Sprintf("GOLC_WAILS_REGISTRY_BUILD_FAILED: %v", err)}
	}
	result := registry.Execute(command.Request{Root: s.root, Args: args})
	return Result{ExitCode: result.ExitCode, Stdout: string(result.Stdout), Stderr: string(result.Stderr)}
}

// scriptCapabilityProfileWire mirrors internal/command/script.go's
// scriptCapabilityProfileView JSON shape exactly, so this package can
// strictjson.DecodeStrict "script list"/"script show"'s Stdout without
// duplicating parsing logic.
type scriptCapabilityProfileWire struct {
	Scope           string `json:"scope"`
	Preset          string `json:"preset"`
	DeadlineSeconds int    `json:"deadline_seconds"`
	RatePerSecond   int    `json:"rate_per_second"`
	MemoryLimitMB   int    `json:"memory_limit_mb"`
	CPUCapPercent   int    `json:"cpu_cap_percent"`
}

// scriptListEntryWire mirrors internal/command/script.go's
// scriptListEntryView JSON shape exactly ("script list"'s per-script
// payload -- no Source).
type scriptListEntryWire struct {
	ID                string                      `json:"id"`
	Name              string                      `json:"name"`
	LastRunStatus     string                      `json:"last_run_status"`
	LastRunReason     string                      `json:"last_run_reason,omitempty"`
	CapabilityProfile scriptCapabilityProfileWire `json:"capability_profile"`
}

// scriptWire mirrors internal/command/script.go's scriptView JSON shape
// exactly (the full per-script payload "script create"/"script show"/
// "script edit" write to Stdout, including Source).
type scriptWire struct {
	ID                string                      `json:"id"`
	Name              string                      `json:"name"`
	Source            string                      `json:"source"`
	CapabilityProfile scriptCapabilityProfileWire `json:"capability_profile"`
	LastRunStatus     string                      `json:"last_run_status"`
	LastRunReason     string                      `json:"last_run_reason,omitempty"`
	LastRunAt         string                      `json:"last_run_at,omitempty"`
}

// ScriptSummaryView is the D-16 library-row projection: one script's
// identity, last-run status, and flattened capability-profile summary
// (Source omitted -- mirrors "script list"'s own cheap-listing rationale).
type ScriptSummaryView struct {
	ID              string `json:"id"`
	Name            string `json:"name"`
	LastRunStatus   string `json:"lastRunStatus"`
	LastRunReason   string `json:"lastRunReason,omitempty"`
	Scope           string `json:"scope"`
	Preset          string `json:"preset"`
	DeadlineSeconds int    `json:"deadlineSeconds"`
	RatePerSecond   int    `json:"ratePerSecond"`
	MemoryLimitMB   int    `json:"memoryLimitMB"`
	CPUCapPercent   int    `json:"cpuCapPercent"`
}

// ScriptDetailView is GetScript's return shape: ScriptSummaryView's fields
// plus Source, the script's full TypeScript text.
type ScriptDetailView struct {
	ScriptSummaryView
	Source string `json:"source"`
}

// summaryFromProfile flattens id, name, lastRunStatus/Reason, and a
// scriptCapabilityProfileWire into ScriptSummaryView -- shared by
// ListScripts (from scriptListEntryWire) and GetScript (from scriptWire).
func summaryFromProfile(id, name, lastRunStatus, lastRunReason string, profile scriptCapabilityProfileWire) ScriptSummaryView {
	return ScriptSummaryView{
		ID:              id,
		Name:            name,
		LastRunStatus:   lastRunStatus,
		LastRunReason:   lastRunReason,
		Scope:           profile.Scope,
		Preset:          profile.Preset,
		DeadlineSeconds: profile.DeadlineSeconds,
		RatePerSecond:   profile.RatePerSecond,
		MemoryLimitMB:   profile.MemoryLimitMB,
		CPUCapPercent:   profile.CPUCapPercent,
	}
}

// ListScripts returns a []ScriptSummaryView decoded from "script list"'s
// JSON (D-16), or an error when the show cannot be read (a non-zero exit
// from the CLI route, or a malformed/unparseable Stdout payload). A show
// with no scripts returns an explicit empty (non-nil) slice.
func (s *ScriptService) ListScripts() ([]ScriptSummaryView, error) {
	result := s.execute("script", "list", "--show", s.showPath)
	if result.ExitCode != 0 {
		return nil, fmt.Errorf("%s", result.Stderr)
	}

	var wire []scriptListEntryWire
	if err := strictjson.DecodeStrict([]byte(result.Stdout), &wire); err != nil {
		return nil, fmt.Errorf("GOLC_WAILS_SCRIPT_LIST_DECODE_FAILED: %v", err)
	}

	views := make([]ScriptSummaryView, 0, len(wire))
	for _, w := range wire {
		views = append(views, summaryFromProfile(w.ID, w.Name, w.LastRunStatus, w.LastRunReason, w.CapabilityProfile))
	}
	return views, nil
}

// GetScript returns a ScriptDetailView (including Source) decoded from
// "script show <name>"'s JSON. An unknown script name surfaces the route's
// own GOLC_SCRIPT_NOT_FOUND diagnostic as the returned error.
func (s *ScriptService) GetScript(name string) (ScriptDetailView, error) {
	result := s.execute("script", "show", name, "--show", s.showPath)
	if result.ExitCode != 0 {
		return ScriptDetailView{}, fmt.Errorf("%s", result.Stderr)
	}

	var wire scriptWire
	if err := strictjson.DecodeStrict([]byte(result.Stdout), &wire); err != nil {
		return ScriptDetailView{}, fmt.Errorf("GOLC_WAILS_SCRIPT_SHOW_DECODE_FAILED: %v", err)
	}

	return ScriptDetailView{
		ScriptSummaryView: summaryFromProfile(wire.ID, wire.Name, wire.LastRunStatus, wire.LastRunReason, wire.CapabilityProfile),
		Source:            wire.Source,
	}, nil
}

// CreateScript creates a new named, empty script via "script create <name>
// --show <path>" (SCRP-01): Result{ExitCode:0} on success,
// Result{ExitCode:1, Stderr: "...GOLC_SCRIPT_NAME_DUPLICATE..."} when name
// is already taken.
func (s *ScriptService) CreateScript(name string) Result {
	return s.execute("script", "create", name, "--show", s.showPath)
}

// SaveScriptSource persists source verbatim as the named script's Source
// (D-14) via "script edit <name> --source-file <path> --show <path>" --
// see the package doc comment for the temp-file argv-safety rationale
// (T-08-12). A source exceeding maxScriptSourceBytes is rejected with
// GOLC_SCRIPT_SOURCE_TOO_LARGE before any temp file is written.
func (s *ScriptService) SaveScriptSource(name, source string) Result {
	if len(source) > maxScriptSourceBytes {
		return Result{ExitCode: 1, Stderr: fmt.Sprintf(
			"GOLC_SCRIPT_SOURCE_TOO_LARGE: source is %d bytes, exceeding the %d byte maximum", len(source), maxScriptSourceBytes)}
	}

	tempFile, err := os.CreateTemp("", "golc-script-source-*.ts")
	if err != nil {
		return Result{ExitCode: 1, Stderr: fmt.Sprintf("GOLC_WAILS_SCRIPT_TEMP_FILE_FAILED: %v", err)}
	}
	tempPath := tempFile.Name()
	defer os.Remove(tempPath)

	if _, writeErr := tempFile.WriteString(source); writeErr != nil {
		_ = tempFile.Close()
		return Result{ExitCode: 1, Stderr: fmt.Sprintf("GOLC_WAILS_SCRIPT_TEMP_FILE_FAILED: %v", writeErr)}
	}
	if closeErr := tempFile.Close(); closeErr != nil {
		return Result{ExitCode: 1, Stderr: fmt.Sprintf("GOLC_WAILS_SCRIPT_TEMP_FILE_FAILED: %v", closeErr)}
	}

	return s.execute("script", "edit", name, "--source-file", tempPath, "--show", s.showPath)
}

// DeleteScript removes the named script via "script delete <name> --show
// <path>"; a subsequent ListScripts omits it. An unknown script name
// surfaces the route's own GOLC_SCRIPT_NOT_FOUND diagnostic.
func (s *ScriptService) DeleteScript(name string) Result {
	return s.execute("script", "delete", name, "--show", s.showPath)
}

// appendPositiveIntFlag appends --flagName <value> to args when value is
// strictly positive -- the shared "only forward what the caller actually
// supplied" rule SetScriptProfile applies to every numeric limit field
// (D-09's partial-edit discipline: an omitted/non-positive field must
// never overwrite the script's existing saved value).
func appendPositiveIntFlag(args []string, flagName string, value int) []string {
	if value > 0 {
		return append(args, "--"+flagName, strconv.Itoa(value))
	}
	return args
}

// SetScriptProfile sets the named script's saved capability/resource-limit
// profile via "script profile set <name> [...] --show <path>" (D-07/D-09),
// forwarding only the non-empty/positive values as flags -- an empty
// scope/preset or a non-positive numeric limit is omitted from the CLI
// invocation entirely, leaving that field untouched on the existing
// profile (mirrors internal/command/script.go's runScriptProfileSet
// partial-edit discipline exactly).
func (s *ScriptService) SetScriptProfile(name, scope, preset string, deadlineSeconds, ratePerSecond, memoryLimitMB, cpuCapPercent int) Result {
	args := []string{"script", "profile", "set", name}
	if scope != "" {
		args = append(args, "--scope", scope)
	}
	if preset != "" {
		args = append(args, "--preset", preset)
	}
	args = appendPositiveIntFlag(args, "deadline-seconds", deadlineSeconds)
	args = appendPositiveIntFlag(args, "rate-per-second", ratePerSecond)
	args = appendPositiveIntFlag(args, "memory-limit-mb", memoryLimitMB)
	args = appendPositiveIntFlag(args, "cpu-cap-percent", cpuCapPercent)
	args = append(args, "--show", s.showPath)
	return s.execute(args...)
}

// scriptRunOutcomeWire mirrors internal/command/scriptrun.go's
// scriptRunOutcomeView JSON shape exactly -- one CallOutcome entry within
// "script run"/"script debug"/"script stop"'s shared Stdout payload
// (scriptstop.go reuses scriptrun.go's toScriptRunResultView directly).
type scriptRunOutcomeWire struct {
	Method     string `json:"method"`
	Route      string `json:"route,omitempty"`
	DurationMS int64  `json:"duration_ms"`
	Ok         bool   `json:"ok"`
	Code       string `json:"code,omitempty"`
	Message    string `json:"message,omitempty"`
}

// scriptRunLogWire mirrors internal/command/scriptrun.go's
// scriptRunLogView JSON shape exactly.
type scriptRunLogWire struct {
	Level   string `json:"level"`
	Message string `json:"message"`
	Source  string `json:"source,omitempty"`
}

// scriptRunResultWire mirrors internal/command/scriptrun.go's
// scriptRunResultView JSON shape exactly -- the uniform Stdout payload
// "script run", "script debug", and "script stop" all write.
type scriptRunResultWire struct {
	RunID    string                 `json:"run_id"`
	Status   string                 `json:"status"`
	Reason   string                 `json:"reason,omitempty"`
	Outcomes []scriptRunOutcomeWire `json:"outcomes"`
	Logs     []scriptRunLogWire     `json:"logs"`
}

// ScriptRunOutcomeEntryView is the JSON-safe Wails projection of one
// script.CallOutcome (D-05: every command outcome, individually).
type ScriptRunOutcomeEntryView struct {
	Method     string `json:"method"`
	Route      string `json:"route,omitempty"`
	DurationMS int64  `json:"durationMs"`
	Ok         bool   `json:"ok"`
	Code       string `json:"code,omitempty"`
	Message    string `json:"message,omitempty"`
}

// ScriptRunLogView is the JSON-safe Wails projection of one script.LogLine
// (D-04's live log/diagnostics stream, as replayed in a run's own final
// outcome).
type ScriptRunLogView struct {
	Level   string `json:"level"`
	Message string `json:"message"`
	Source  string `json:"source,omitempty"`
}

// ScriptRunOutcomeView is RunScript/DebugScript/StopScript's uniform
// return shape (08-10-PLAN.md Task 1): every field a plain scalar/slice,
// matching this package's own Result convention, so Wails' TypeScript
// binding generator produces a simple type. StackFrames is derived from
// Reason, never a second independently-parsed source of truth:
// internal/script's RunOutcome carries a crash's full captured text --
// Deno's own "Uncaught Error: ..." header line followed by its
// "    at ..." frame lines (D-03), already redacted at internal/script's
// single publication point -- as one multi-line Reason string. There is
// no separately structured []script.StackFrame available outside
// internal/script's own debug-mode CDP path (debugbridge.go's
// framesFromCDPCallFrames, folded into its own formatted exception
// Message rather than exported); splitting Reason's own lines here keeps
// this package from re-implementing or duplicating internal/script's
// redaction/parsing logic a second time.
type ScriptRunOutcomeView struct {
	RunID       string                      `json:"runId"`
	Status      string                      `json:"status"`
	Reason      string                      `json:"reason,omitempty"`
	Logs        []ScriptRunLogView          `json:"logs"`
	Outcomes    []ScriptRunOutcomeEntryView `json:"outcomes"`
	StackFrames []string                    `json:"stackFrames"`
}

// deriveStackFrames splits a terminal Reason string into D-03's
// expandable stack-trace lines: Reason's own first line is the crash
// summary the frontend renders as "Script crashed: {error summary}"
// directly from Reason; every remaining non-blank line is one expandable
// trace entry. A Reason with no second line (a clean success, or a
// failure with no captured trace text) returns an explicit empty (never
// nil) slice.
func deriveStackFrames(reason string) []string {
	frames := make([]string, 0)
	lines := strings.Split(reason, "\n")
	if len(lines) <= 1 {
		return frames
	}
	for _, line := range lines[1:] {
		trimmed := strings.TrimSpace(line)
		if trimmed != "" {
			frames = append(frames, trimmed)
		}
	}
	return frames
}

// toScriptRunOutcomeView projects a decoded scriptRunResultWire into its
// JSON-safe ScriptRunOutcomeView shape. Logs/Outcomes/StackFrames always
// render as present (never nil) slices.
func toScriptRunOutcomeView(wire scriptRunResultWire) ScriptRunOutcomeView {
	logs := make([]ScriptRunLogView, 0, len(wire.Logs))
	for _, l := range wire.Logs {
		logs = append(logs, ScriptRunLogView{Level: l.Level, Message: l.Message, Source: l.Source})
	}
	outcomes := make([]ScriptRunOutcomeEntryView, 0, len(wire.Outcomes))
	for _, o := range wire.Outcomes {
		outcomes = append(outcomes, ScriptRunOutcomeEntryView{
			Method: o.Method, Route: o.Route, DurationMS: o.DurationMS, Ok: o.Ok, Code: o.Code, Message: o.Message,
		})
	}
	return ScriptRunOutcomeView{
		RunID: wire.RunID, Status: wire.Status, Reason: wire.Reason,
		Logs: logs, Outcomes: outcomes, StackFrames: deriveStackFrames(wire.Reason),
	}
}

// decodeRunOutcome decodes a "script run"/"script debug"/"script stop"
// route's Result into a ScriptRunOutcomeView: every one of these three
// routes writes its full run-outcome JSON to Stdout on every reachable
// exit code (0 success, 1 failed/terminated/no-active-run) -- only a
// malformed invocation (ExitCode 2) or a pre-flight failure (e.g.
// GOLC_SCRIPT_NOT_FOUND, a show load failure) never reaches that point and
// therefore never writes Stdout, surfaced here as a returned error
// carrying the route's own Stderr diagnostic verbatim.
func (s *ScriptService) decodeRunOutcome(result Result) (ScriptRunOutcomeView, error) {
	if result.Stdout == "" {
		return ScriptRunOutcomeView{}, fmt.Errorf("%s", result.Stderr)
	}
	var wire scriptRunResultWire
	if err := strictjson.DecodeStrict([]byte(result.Stdout), &wire); err != nil {
		return ScriptRunOutcomeView{}, fmt.Errorf("GOLC_WAILS_SCRIPT_RUN_DECODE_FAILED: %v", err)
	}
	return toScriptRunOutcomeView(wire), nil
}

// RunScript launches name in a fresh, zero-permission Deno process via
// "script run <name> --show <path>" (D-02: a plain Run never opens a
// debug-mode inspector channel), returning the run's full outcome --
// status, reason, captured logs, and every SDK call's individual outcome
// (D-04/D-05) -- decoded from the route's own Stdout JSON.
func (s *ScriptService) RunScript(name string) (ScriptRunOutcomeView, error) {
	result := s.execute("script", "run", name, "--show", s.showPath)
	return s.decodeRunOutcome(result)
}

// DebugScript launches name in Debug mode via "script debug <name>
// --show <path> [--breakpoint <line>...]" (D-01/D-02): breakpointLines
// becomes one repeated --breakpoint flag per entry, mirroring
// internal/command/scriptdebug.go's own repeatable-flag parsing exactly.
// An empty breakpointLines launches with no breakpoints set, resuming
// immediately from the initial break (scriptdebug.go's own documented
// empty-slice behavior).
func (s *ScriptService) DebugScript(name string, breakpointLines []int) (ScriptRunOutcomeView, error) {
	args := []string{"script", "debug", name}
	for _, line := range breakpointLines {
		args = append(args, "--breakpoint", strconv.Itoa(line))
	}
	args = append(args, "--show", s.showPath)
	return s.decodeRunOutcome(s.execute(args...))
}

// StopScript stops name's active run immediately via "script stop <name>
// --show <path>" (D-10: a separate, lightweight, single-script-scoped
// action -- never Phase 6's global Revoke Automation). Returns the raw
// Result (not a decoded ScriptRunOutcomeView) so a caller can distinguish
// "stopped" (ExitCode 0, Stdout carries the run's final outcome JSON) from
// "no active run" (ExitCode 1, Stderr carries GOLC_SCRIPT_NO_ACTIVE_RUN)
// without this method masking the no-active-run case behind a generic
// decode error.
func (s *ScriptService) StopScript(name string) Result {
	return s.execute("script", "stop", name, "--show", s.showPath)
}

// scriptValidateDiagnosticWire mirrors internal/command/scriptvalidate.go's
// scriptValidateDiagnosticView JSON shape exactly.
type scriptValidateDiagnosticWire struct {
	Code     string `json:"code"`
	Message  string `json:"message"`
	Line     int    `json:"line"`
	Column   int    `json:"column"`
	Severity string `json:"severity"`
}

// scriptValidateResultWire mirrors internal/command/scriptvalidate.go's
// scriptValidateResultView JSON shape exactly.
type scriptValidateResultWire struct {
	Valid       bool                           `json:"valid"`
	Diagnostics []scriptValidateDiagnosticWire `json:"diagnostics"`
}

// ScriptDiagnosticView is the JSON-safe Wails projection of one
// script.Diagnostic.
type ScriptDiagnosticView struct {
	Code     string `json:"code"`
	Message  string `json:"message"`
	Line     int    `json:"line"`
	Column   int    `json:"column"`
	Severity string `json:"severity"`
}

// ScriptValidationView is ValidateScript's return shape: valid, plus
// every diagnostic found -- Diagnostics is always a present (never nil)
// slice, mirroring the route's own "never null" JSON contract.
type ScriptValidationView struct {
	Valid       bool                   `json:"valid"`
	Diagnostics []ScriptDiagnosticView `json:"diagnostics"`
}

// ValidateScript runs SCRP-01's validate verb against name via
// "script validate <name> --show <path>" -- the structural zero-import
// gate plus a deno check type-check -- without ever executing the script,
// decoded from the route's own Stdout JSON. A pre-flight failure (an
// unknown script name, a show load failure, or a malformed invocation)
// never writes Stdout, surfaced here as a returned error carrying the
// route's own Stderr diagnostic verbatim.
func (s *ScriptService) ValidateScript(name string) (ScriptValidationView, error) {
	result := s.execute("script", "validate", name, "--show", s.showPath)
	if result.Stdout == "" {
		return ScriptValidationView{}, fmt.Errorf("%s", result.Stderr)
	}

	var wire scriptValidateResultWire
	if err := strictjson.DecodeStrict([]byte(result.Stdout), &wire); err != nil {
		return ScriptValidationView{}, fmt.Errorf("GOLC_WAILS_SCRIPT_VALIDATE_DECODE_FAILED: %v", err)
	}

	diagnostics := make([]ScriptDiagnosticView, 0, len(wire.Diagnostics))
	for _, d := range wire.Diagnostics {
		diagnostics = append(diagnostics, ScriptDiagnosticView{
			Code: d.Code, Message: d.Message, Line: d.Line, Column: d.Column, Severity: d.Severity,
		})
	}
	return ScriptValidationView{Valid: wire.Valid, Diagnostics: diagnostics}, nil
}

// GetSDKTypeDefinitions returns the committed golc.d.ts contents (D-15,
// 08-11-PLAN.md Task 2): Monaco's TypeScript language service loads this
// string as an extra lib, giving live autocomplete/diagnostics against the
// real generated GOLC SDK from a bare `golc.` with nothing imported (the
// file itself declares no import/export -- 08-RESEARCH.md Pitfall 4). A
// missing file (an unbuilt/misconfigured root, or a checkout that skipped
// `go run ./cmd/golc-project generate`) surfaces the named
// GOLC_SCRIPTSDK_TYPES_MISSING diagnostic rather than a raw os.ReadFile
// error, so the frontend can distinguish "types not generated yet" from a
// generic I/O failure.
func (s *ScriptService) GetSDKTypeDefinitions() (string, error) {
	path := filepath.Join(s.root, filepath.FromSlash(scriptSDKTypesRelPath))
	contents, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return "", fmt.Errorf("GOLC_SCRIPTSDK_TYPES_MISSING: %s not found under root %q", scriptSDKTypesRelPath, s.root)
		}
		return "", fmt.Errorf("GOLC_WAILS_SCRIPTSDK_TYPES_READ_FAILED: %v", err)
	}
	return string(contents), nil
}

// ContinueScript resumes the single active debug run via
// "script continue --show <path>"; Result{ExitCode:1} carries
// GOLC_SCRIPT_NO_ACTIVE_DEBUG when none is active or the active run is
// not a debug run (mirrors internal/command/scriptdebug.go's
// runScriptDebugControl exactly -- no --name flag, the same v1 "at most
// one active run globally" scope 08-05 established).
func (s *ScriptService) ContinueScript() Result {
	return s.execute("script", "continue", "--show", s.showPath)
}

// StepOverScript steps over the current statement in the single active
// debug run via "script step-over --show <path>".
func (s *ScriptService) StepOverScript() Result {
	return s.execute("script", "step-over", "--show", s.showPath)
}

// StepIntoScript steps into the current call in the single active debug
// run via "script step-into --show <path>".
func (s *ScriptService) StepIntoScript() Result {
	return s.execute("script", "step-into", "--show", s.showPath)
}

// StepOutScript steps out of the current call in the single active debug
// run via "script step-out --show <path>".
func (s *ScriptService) StepOutScript() Result {
	return s.execute("script", "step-out", "--show", s.showPath)
}

// toScriptEventView projects a script.ScriptEvent (internal/script/
// events.go, 08-08-PLAN.md Task 1) into this package's own JSON-safe
// ScriptEventView shape -- every field a plain string/number/bool, never
// the raw uuid.UUID/show.ScriptRunStatus/time.Time types Wails' TypeScript
// binding generator cannot render directly.
func toScriptEventView(ev script.ScriptEvent) ScriptEventView {
	return ScriptEventView{
		Seq:        ev.Seq,
		Kind:       string(ev.Kind),
		RunID:      ev.RunID.String(),
		ScriptName: ev.ScriptName,
		At:         ev.At.Format(time.RFC3339Nano),
		Level:      ev.Level,
		Message:    ev.Message,
		Source:     ev.Source,
		Method:     ev.Method,
		Route:      ev.Route,
		DurationMS: ev.DurationMS,
		Ok:         ev.Ok,
		Code:       ev.Code,
		Status:     string(ev.Status),
		Reason:     ev.Reason,
	}
}

// StartScriptEventStream begins forwarding every live script.ScriptEvent
// (D-04/D-05, 08-08-PLAN.md Task 3) from internal/script's process-wide bus
// to the desktop webview: it starts this service's own throttled
// EventPusher flush loop (mirrors SafetyService.StartStatusPush's own
// s.events.Start(ctx) call), subscribes to script.SubscribeScriptEvents
// with no prior Seq (a fresh live subscription -- no replay), and runs a
// forwarding goroutine that stages each received event via
// QueueScriptEvent until StopScriptEventStream cancels it or the
// subscription channel closes. Calling StartScriptEventStream again
// without an intervening StopScriptEventStream is a no-op (mirrors
// EventPusher.Start's own idempotency).
func (s *ScriptService) StartScriptEventStream(ctx context.Context) {
	s.mu.Lock()
	if s.streamCancel != nil {
		s.mu.Unlock()
		return
	}
	streamCtx, cancel := context.WithCancel(ctx)
	s.streamCancel = cancel
	s.streamDone = make(chan struct{})
	s.mu.Unlock()

	s.events.Start(ctx)

	_, _, ch, unsubscribe := script.SubscribeScriptEvents(0)
	go s.forwardScriptEvents(streamCtx, ch, unsubscribe)
}

// forwardScriptEvents drains ch (the live subscription StartScriptEventStream
// opened) until ctx is done (StopScriptEventStream) or ch closes, staging
// every received event via QueueScriptEvent so EventPusher's own flush
// loop emits it under "script:event" -- ordered, non-coalescing (Task 3's
// exact requirement). unsubscribe is always called on exit, and
// streamDone is always closed exactly once, so StopScriptEventStream can
// block until this goroutine has actually finished.
func (s *ScriptService) forwardScriptEvents(ctx context.Context, ch chan script.ScriptEvent, unsubscribe func()) {
	defer close(s.streamDone)
	defer unsubscribe()
	for {
		select {
		case <-ctx.Done():
			return
		case ev, ok := <-ch:
			if !ok {
				return
			}
			s.events.QueueScriptEvent(toScriptEventView(ev))
		}
	}
}

// StopScriptEventStream cancels the forwarding goroutine, waits for it to
// exit (guaranteeing unsubscribe has already run), and stops the
// underlying EventPusher -- mirrors SafetyService.StopStatusPush's own
// reverse-order subsystem stop discipline. Safe to call more than once or
// before StartScriptEventStream.
func (s *ScriptService) StopScriptEventStream() {
	s.mu.Lock()
	cancel := s.streamCancel
	done := s.streamDone
	s.streamCancel = nil
	s.mu.Unlock()
	if cancel == nil {
		return
	}
	cancel()
	if done != nil {
		<-done
	}
	s.events.Stop()
}
